#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ANIMBP_Fiveseven

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function ANIMBP_Fiveseven.ANIMBP_Fiveseven_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct ANIMBP_Fiveseven_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
static_assert(alignof(ANIMBP_Fiveseven_C_AnimGraph) == 0x000008, "Wrong alignment on ANIMBP_Fiveseven_C_AnimGraph");
static_assert(sizeof(ANIMBP_Fiveseven_C_AnimGraph) == 0x000010, "Wrong size on ANIMBP_Fiveseven_C_AnimGraph");
static_assert(offsetof(ANIMBP_Fiveseven_C_AnimGraph, AnimGraph_0) == 0x000000, "Member 'ANIMBP_Fiveseven_C_AnimGraph::AnimGraph_0' has a wrong offset!");

// Function ANIMBP_Fiveseven.ANIMBP_Fiveseven_C.BlueprintUpdateAnimation
// 0x0004 (0x0004 - 0x0000)
struct ANIMBP_Fiveseven_C_BlueprintUpdateAnimation final
{
public:
	float                                         DeltaTimeX;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ANIMBP_Fiveseven_C_BlueprintUpdateAnimation) == 0x000004, "Wrong alignment on ANIMBP_Fiveseven_C_BlueprintUpdateAnimation");
static_assert(sizeof(ANIMBP_Fiveseven_C_BlueprintUpdateAnimation) == 0x000004, "Wrong size on ANIMBP_Fiveseven_C_BlueprintUpdateAnimation");
static_assert(offsetof(ANIMBP_Fiveseven_C_BlueprintUpdateAnimation, DeltaTimeX) == 0x000000, "Member 'ANIMBP_Fiveseven_C_BlueprintUpdateAnimation::DeltaTimeX' has a wrong offset!");

// Function ANIMBP_Fiveseven.ANIMBP_Fiveseven_C.ExecuteUbergraph_ANIMBP_Fiveseven
// 0x0028 (0x0028 - 0x0000)
struct ANIMBP_Fiveseven_C_ExecuteUbergraph_ANIMBP_Fiveseven final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Round_ReturnValue;                        // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Round_ReturnValue_1;                      // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x000D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E[0x2];                                        // 0x000E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Event_DeltaTimeX;                           // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Round_A_ImplicitCast;                     // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Round_A_ImplicitCast_1;                   // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ANIMBP_Fiveseven_C_ExecuteUbergraph_ANIMBP_Fiveseven) == 0x000008, "Wrong alignment on ANIMBP_Fiveseven_C_ExecuteUbergraph_ANIMBP_Fiveseven");
static_assert(sizeof(ANIMBP_Fiveseven_C_ExecuteUbergraph_ANIMBP_Fiveseven) == 0x000028, "Wrong size on ANIMBP_Fiveseven_C_ExecuteUbergraph_ANIMBP_Fiveseven");
static_assert(offsetof(ANIMBP_Fiveseven_C_ExecuteUbergraph_ANIMBP_Fiveseven, EntryPoint) == 0x000000, "Member 'ANIMBP_Fiveseven_C_ExecuteUbergraph_ANIMBP_Fiveseven::EntryPoint' has a wrong offset!");
static_assert(offsetof(ANIMBP_Fiveseven_C_ExecuteUbergraph_ANIMBP_Fiveseven, CallFunc_Round_ReturnValue) == 0x000004, "Member 'ANIMBP_Fiveseven_C_ExecuteUbergraph_ANIMBP_Fiveseven::CallFunc_Round_ReturnValue' has a wrong offset!");
static_assert(offsetof(ANIMBP_Fiveseven_C_ExecuteUbergraph_ANIMBP_Fiveseven, CallFunc_Round_ReturnValue_1) == 0x000008, "Member 'ANIMBP_Fiveseven_C_ExecuteUbergraph_ANIMBP_Fiveseven::CallFunc_Round_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ANIMBP_Fiveseven_C_ExecuteUbergraph_ANIMBP_Fiveseven, CallFunc_Less_IntInt_ReturnValue) == 0x00000C, "Member 'ANIMBP_Fiveseven_C_ExecuteUbergraph_ANIMBP_Fiveseven::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(ANIMBP_Fiveseven_C_ExecuteUbergraph_ANIMBP_Fiveseven, CallFunc_Less_IntInt_ReturnValue_1) == 0x00000D, "Member 'ANIMBP_Fiveseven_C_ExecuteUbergraph_ANIMBP_Fiveseven::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ANIMBP_Fiveseven_C_ExecuteUbergraph_ANIMBP_Fiveseven, K2Node_Event_DeltaTimeX) == 0x000010, "Member 'ANIMBP_Fiveseven_C_ExecuteUbergraph_ANIMBP_Fiveseven::K2Node_Event_DeltaTimeX' has a wrong offset!");
static_assert(offsetof(ANIMBP_Fiveseven_C_ExecuteUbergraph_ANIMBP_Fiveseven, CallFunc_Round_A_ImplicitCast) == 0x000018, "Member 'ANIMBP_Fiveseven_C_ExecuteUbergraph_ANIMBP_Fiveseven::CallFunc_Round_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(ANIMBP_Fiveseven_C_ExecuteUbergraph_ANIMBP_Fiveseven, CallFunc_Round_A_ImplicitCast_1) == 0x000020, "Member 'ANIMBP_Fiveseven_C_ExecuteUbergraph_ANIMBP_Fiveseven::CallFunc_Round_A_ImplicitCast_1' has a wrong offset!");

}

