#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AudioControlButtonStyle

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AudioControlButtonStyle.AudioControlButtonStyle_C
// 0x0000 (0x07C0 - 0x07C0)
class UAudioControlButtonStyle_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AudioControlButtonStyle_C">();
	}
	static class UAudioControlButtonStyle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAudioControlButtonStyle_C>();
	}
};
static_assert(alignof(UAudioControlButtonStyle_C) == 0x000010, "Wrong alignment on UAudioControlButtonStyle_C");
static_assert(sizeof(UAudioControlButtonStyle_C) == 0x0007C0, "Wrong size on UAudioControlButtonStyle_C");

}

