#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Primary_Mossberg590Mv2

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Primary_Mossberg590Mv2.BP_Primary_Mossberg590Mv2_C
// 0x0010 (0x18C0 - 0x18B0)
class ABP_Primary_Mossberg590Mv2_C final : public ABaseMagazineWeapon
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x18B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_Primary_Mossberg590Mv2(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Primary_Mossberg590Mv2_C">();
	}
	static class ABP_Primary_Mossberg590Mv2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Primary_Mossberg590Mv2_C>();
	}
};
static_assert(alignof(ABP_Primary_Mossberg590Mv2_C) == 0x000010, "Wrong alignment on ABP_Primary_Mossberg590Mv2_C");
static_assert(sizeof(ABP_Primary_Mossberg590Mv2_C) == 0x0018C0, "Wrong size on ABP_Primary_Mossberg590Mv2_C");
static_assert(offsetof(ABP_Primary_Mossberg590Mv2_C, UberGraphFrame) == 0x0018B0, "Member 'ABP_Primary_Mossberg590Mv2_C::UberGraphFrame' has a wrong offset!");

}

