#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ReplayController

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ReplayController.BP_ReplayController_C
// 0x0040 (0x0E10 - 0x0DD0)
class ABP_ReplayController_C final : public AReplayController
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0DD0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          bRemoveReplayControls;                             // 0x0DD8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bSetInitialPosition;                               // 0x0DD9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bSprintHeld;                                       // 0x0DDA(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bCrouchHeld;                                       // 0x0DDB(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bFollowLocalPlayer;                                // 0x0DDC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DDD[0x3];                                      // 0x0DDD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class AReadyOrNotCharacter*                   LocalPlayer;                                       // 0x0DE0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	double                                        DeltaSeconds;                                      // 0x0DE8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class ABaseItem*>                      IgnoredActors;                                     // 0x0DF0(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	bool                                          MouseRightPressed;                                 // 0x0E00(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E01[0x3];                                      // 0x0E01(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         HUDState;                                          // 0x0E04(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bPrePaused;                                        // 0x0E08(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_ReplayController(int32 EntryPoint);
	void InpActEvt_ReplayDecreasePlaybackSpeed_K2Node_InputActionEvent_0(const struct FKey& Key);
	void InpActEvt_ReplayDecreasePlaybackSpeed_K2Node_InputActionEvent_1(const struct FKey& Key);
	void InpActEvt_ReplayIncreasePlaybackSpeed_K2Node_InputActionEvent_2(const struct FKey& Key);
	void InpActEvt_ReplayIncreasePlaybackSpeed_K2Node_InputActionEvent_3(const struct FKey& Key);
	void OnPauseMenuClosed();
	void OnPauseMenuOpened();
	void OnScrubComplete();
	void ToggleReplayHUD();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ReplayController_C">();
	}
	static class ABP_ReplayController_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ReplayController_C>();
	}
};
static_assert(alignof(ABP_ReplayController_C) == 0x000008, "Wrong alignment on ABP_ReplayController_C");
static_assert(sizeof(ABP_ReplayController_C) == 0x000E10, "Wrong size on ABP_ReplayController_C");
static_assert(offsetof(ABP_ReplayController_C, UberGraphFrame) == 0x000DD0, "Member 'ABP_ReplayController_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_ReplayController_C, bRemoveReplayControls) == 0x000DD8, "Member 'ABP_ReplayController_C::bRemoveReplayControls' has a wrong offset!");
static_assert(offsetof(ABP_ReplayController_C, bSetInitialPosition) == 0x000DD9, "Member 'ABP_ReplayController_C::bSetInitialPosition' has a wrong offset!");
static_assert(offsetof(ABP_ReplayController_C, bSprintHeld) == 0x000DDA, "Member 'ABP_ReplayController_C::bSprintHeld' has a wrong offset!");
static_assert(offsetof(ABP_ReplayController_C, bCrouchHeld) == 0x000DDB, "Member 'ABP_ReplayController_C::bCrouchHeld' has a wrong offset!");
static_assert(offsetof(ABP_ReplayController_C, bFollowLocalPlayer) == 0x000DDC, "Member 'ABP_ReplayController_C::bFollowLocalPlayer' has a wrong offset!");
static_assert(offsetof(ABP_ReplayController_C, LocalPlayer) == 0x000DE0, "Member 'ABP_ReplayController_C::LocalPlayer' has a wrong offset!");
static_assert(offsetof(ABP_ReplayController_C, DeltaSeconds) == 0x000DE8, "Member 'ABP_ReplayController_C::DeltaSeconds' has a wrong offset!");
static_assert(offsetof(ABP_ReplayController_C, IgnoredActors) == 0x000DF0, "Member 'ABP_ReplayController_C::IgnoredActors' has a wrong offset!");
static_assert(offsetof(ABP_ReplayController_C, MouseRightPressed) == 0x000E00, "Member 'ABP_ReplayController_C::MouseRightPressed' has a wrong offset!");
static_assert(offsetof(ABP_ReplayController_C, HUDState) == 0x000E04, "Member 'ABP_ReplayController_C::HUDState' has a wrong offset!");
static_assert(offsetof(ABP_ReplayController_C, bPrePaused) == 0x000E08, "Member 'ABP_ReplayController_C::bPrePaused' has a wrong offset!");

}

