#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_CommanderProfileSelect

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "ReadyOrNot_structs.hpp"
#include "UMG_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.BndEvt__W_CommanderProfileSelect_Example_BackButton_1_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_Example_BackButton_1_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature final
{
public:
	class UW_Button_C*                            Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_Example_BackButton_1_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature) == 0x000008, "Wrong alignment on W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_Example_BackButton_1_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature");
static_assert(sizeof(W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_Example_BackButton_1_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature) == 0x000008, "Wrong size on W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_Example_BackButton_1_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature");
static_assert(offsetof(W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_Example_BackButton_1_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature, Button) == 0x000000, "Member 'W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_Example_BackButton_1_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature::Button' has a wrong offset!");

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.BndEvt__W_CommanderProfileSelect_PageWrapper_K2Node_ComponentBoundEvent_2_OnFooterButtonClicked__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_PageWrapper_K2Node_ComponentBoundEvent_2_OnFooterButtonClicked__DelegateSignature final
{
public:
	class FString                                 ButtonId;                                          // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_PageWrapper_K2Node_ComponentBoundEvent_2_OnFooterButtonClicked__DelegateSignature) == 0x000008, "Wrong alignment on W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_PageWrapper_K2Node_ComponentBoundEvent_2_OnFooterButtonClicked__DelegateSignature");
static_assert(sizeof(W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_PageWrapper_K2Node_ComponentBoundEvent_2_OnFooterButtonClicked__DelegateSignature) == 0x000010, "Wrong size on W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_PageWrapper_K2Node_ComponentBoundEvent_2_OnFooterButtonClicked__DelegateSignature");
static_assert(offsetof(W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_PageWrapper_K2Node_ComponentBoundEvent_2_OnFooterButtonClicked__DelegateSignature, ButtonId) == 0x000000, "Member 'W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_PageWrapper_K2Node_ComponentBoundEvent_2_OnFooterButtonClicked__DelegateSignature::ButtonId' has a wrong offset!");

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.CancelDelete
// 0x0008 (0x0008 - 0x0000)
struct W_CommanderProfileSelect_C_CancelDelete final
{
public:
	class UStandardModal*                         CallingModal;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_CommanderProfileSelect_C_CancelDelete) == 0x000008, "Wrong alignment on W_CommanderProfileSelect_C_CancelDelete");
static_assert(sizeof(W_CommanderProfileSelect_C_CancelDelete) == 0x000008, "Wrong size on W_CommanderProfileSelect_C_CancelDelete");
static_assert(offsetof(W_CommanderProfileSelect_C_CancelDelete, CallingModal) == 0x000000, "Member 'W_CommanderProfileSelect_C_CancelDelete::CallingModal' has a wrong offset!");

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.DeleteSave
// 0x0020 (0x0020 - 0x0000)
struct W_CommanderProfileSelect_C_DeleteSave final
{
public:
	class UW_StandardModal_C*                     CallingModal;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FText                                   TextEntry;                                         // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(W_CommanderProfileSelect_C_DeleteSave) == 0x000008, "Wrong alignment on W_CommanderProfileSelect_C_DeleteSave");
static_assert(sizeof(W_CommanderProfileSelect_C_DeleteSave) == 0x000020, "Wrong size on W_CommanderProfileSelect_C_DeleteSave");
static_assert(offsetof(W_CommanderProfileSelect_C_DeleteSave, CallingModal) == 0x000000, "Member 'W_CommanderProfileSelect_C_DeleteSave::CallingModal' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_DeleteSave, TextEntry) == 0x000008, "Member 'W_CommanderProfileSelect_C_DeleteSave::TextEntry' has a wrong offset!");

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.ExecuteUbergraph_W_CommanderProfileSelect
// 0x0320 (0x0320 - 0x0000)
struct W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateChildSize                        K2Node_MakeStruct_SlateChildSize;                  // 0x0004(0x0008)(NoDestructor)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x000D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E[0x2];                                        // 0x000E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_2;                  // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UW_Button_C*                            K2Node_ComponentBoundEvent_Button;                 // 0x0038(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_CommanderProfileCard_C*              K2Node_CustomEvent_TriggeringProfileCard_1;        // 0x0048(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_Hovered;                        // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable;                                // 0x0058(0x0018)(ConstParm)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x0071(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_72[0x2];                                       // 0x0072(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable;                                 // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0079(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7A[0x2];                                       // 0x007A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_4;                 // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0080(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_BC[0x4];                                       // 0x00BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable_1;                              // 0x00C0(0x0018)(ConstParm)
	int32                                         Temp_int_Array_Index_Variable_2;                   // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_3;                   // 0x00DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_4;                   // 0x00E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E4[0x4];                                       // 0x00E4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommanderProfile*                      CallFunc_LoadProfile_ReturnValue;                  // 0x00E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UW_CommanderProfileCard_C*              CallFunc_Create_ReturnValue;                       // 0x00F0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UW_StandardModal_C*                     CallFunc_Create_ReturnValue_1;                     // 0x00F8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UW_CommanderProfileCard_C* TriggeringProfileCard, bool Hovered)> K2Node_CreateDelegate_OutputDelegate; // 0x0100(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UW_CommanderProfileCard_C*              K2Node_CustomEvent_TriggeringProfileCard;          // 0x0110(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UW_CommanderProfileCard_C* TriggeringProfileCard)> K2Node_CreateDelegate_OutputDelegate_1; // 0x0118(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UW_StandardModal_C*                     K2Node_CustomEvent_CallingModal_1;                 // 0x0128(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FText                                   K2Node_CustomEvent_TextEntry;                      // 0x0130(0x0018)()
	class UStandardModal*                         K2Node_CustomEvent_CallingModal;                   // 0x0148(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_3;                  // 0x0150(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_5;                 // 0x0154(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 K2Node_ComponentBoundEvent_ButtonID;               // 0x0158(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchString_CmpSuccess;                    // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_169[0x7];                                      // 0x0169(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_CommanderProfileCard_C*              K2Node_CustomEvent_SelectedProfileCard_1;          // 0x0170(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UW_CommanderProfileCard_C* CommanderProfileCardReference)> K2Node_CreateDelegate_OutputDelegate_2; // 0x0178(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_4;                  // 0x0188(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x018C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_18D[0x3];                                      // 0x018D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_6;                 // 0x0190(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_194[0x4];                                      // 0x0194(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_CommanderProfileCard_C*              K2Node_DynamicCast_AsW_Commander_Profile_Card;     // 0x0198(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x01A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1A1[0x7];                                      // 0x01A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_CommanderProfileCard_C*              K2Node_CustomEvent_SelectedProfileCard;            // 0x01A8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UW_CommanderProfileCard_C*              CallFunc_Array_Get_Item;                           // 0x01B0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x01B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x01B9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x01BA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1BB[0x5];                                      // 0x01BB(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UHorizontalBoxSlot*                     CallFunc_SlotAsHorizontalBoxSlot_ReturnValue;      // 0x01C0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x01C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x01CC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_MakeLiteralBool_ReturnValue;              // 0x01CD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1CE[0x2];                                      // 0x01CE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable_2;                              // 0x01D0(0x0018)(ConstParm)
	struct FVector2D                              Temp_struct_Variable;                              // 0x01E8(0x0010)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x01F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1FC[0x4];                                      // 0x01FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UHorizontalBoxSlot*                     CallFunc_AddChildToHorizontalBox_ReturnValue;      // 0x0200(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UW_CommanderProfileCard_C*              CallFunc_Array_Get_Item_1;                         // 0x0208(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0210(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0214(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_215[0x3];                                      // 0x0215(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UHorizontalBoxSlot*                     CallFunc_AddChildToHorizontalBox_ReturnValue_1;    // 0x0218(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UW_CommanderProfileCard_C*              CallFunc_Array_Get_Item_2;                         // 0x0220(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UW_CommanderProfileCard_C*              CallFunc_Array_Get_Item_3;                         // 0x0228(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x0230(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_3;               // 0x0234(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x0238(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_3;                // 0x0239(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_23A[0x2];                                      // 0x023A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateChildSize                        K2Node_MakeStruct_SlateChildSize_1;                // 0x023C(0x0008)(NoDestructor)
	uint8                                         Pad_244[0x4];                                      // 0x0244(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_CommanderProfileCard_C*              CallFunc_Array_Get_Item_4;                         // 0x0248(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UW_CommanderProfileCard_C*              CallFunc_Array_Get_Item_5;                         // 0x0250(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0258(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_259[0x7];                                      // 0x0259(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_CommanderProfileCard_C*              CallFunc_Array_Get_Item_6;                         // 0x0260(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UW_CommanderProfileCard_C*              CallFunc_Array_Get_Item_7;                         // 0x0268(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x0270(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_271[0x3];                                      // 0x0271(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_4;               // 0x0274(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_4;                // 0x0278(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_279[0x3];                                      // 0x0279(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UStandardModal* CallingModal)> K2Node_CreateDelegate_OutputDelegate_3;      // 0x027C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_7;                 // 0x028C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UW_StandardModal_C* CallingModal, class FText TextEntry)> K2Node_CreateDelegate_OutputDelegate_4; // 0x0290(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int64                                         CallFunc_Conv_IntToInt64_ReturnValue;              // 0x02A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x02A8(0x0050)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x02F8(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0308(0x0018)()
};
static_assert(alignof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect) == 0x000008, "Wrong alignment on W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect");
static_assert(sizeof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect) == 0x000320, "Wrong size on W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, EntryPoint) == 0x000000, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::EntryPoint' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_MakeStruct_SlateChildSize) == 0x000004, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_MakeStruct_SlateChildSize' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, Temp_bool_IsClosed_Variable) == 0x00000C, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, Temp_bool_Has_Been_Initd_Variable) == 0x00000D, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, Temp_int_Loop_Counter_Variable) == 0x000010, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Add_IntInt_ReturnValue) == 0x000014, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_IsValid_ReturnValue) == 0x000018, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, Temp_int_Loop_Counter_Variable_1) == 0x00001C, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Add_IntInt_ReturnValue_1) == 0x000020, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, Temp_int_Array_Index_Variable) == 0x000024, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, Temp_int_Loop_Counter_Variable_2) == 0x000028, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::Temp_int_Loop_Counter_Variable_2' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Subtract_IntInt_ReturnValue) == 0x00002C, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Add_IntInt_ReturnValue_2) == 0x000030, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Add_IntInt_ReturnValue_3) == 0x000034, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_ComponentBoundEvent_Button) == 0x000038, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_ComponentBoundEvent_Button' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, Temp_int_Array_Index_Variable_1) == 0x000040, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_CustomEvent_TriggeringProfileCard_1) == 0x000048, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_CustomEvent_TriggeringProfileCard_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_CustomEvent_Hovered) == 0x000050, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_CustomEvent_Hovered' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, Temp_text_Variable) == 0x000058, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::Temp_text_Variable' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Not_PreBool_ReturnValue) == 0x000070, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_NotEqual_ObjectObject_ReturnValue) == 0x000071, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_NotEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, Temp_int_Variable) == 0x000074, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_IsValid_ReturnValue_1) == 0x000078, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_LessEqual_IntInt_ReturnValue) == 0x000079, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Add_IntInt_ReturnValue_4) == 0x00007C, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Add_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_Event_MyGeometry) == 0x000080, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_Event_InDeltaTime) == 0x0000B8, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_Event_InDeltaTime' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, Temp_text_Variable_1) == 0x0000C0, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::Temp_text_Variable_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, Temp_int_Array_Index_Variable_2) == 0x0000D8, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::Temp_int_Array_Index_Variable_2' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, Temp_int_Array_Index_Variable_3) == 0x0000DC, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::Temp_int_Array_Index_Variable_3' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, Temp_int_Array_Index_Variable_4) == 0x0000E0, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::Temp_int_Array_Index_Variable_4' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_LoadProfile_ReturnValue) == 0x0000E8, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_LoadProfile_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Create_ReturnValue) == 0x0000F0, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Create_ReturnValue_1) == 0x0000F8, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Create_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_CreateDelegate_OutputDelegate) == 0x000100, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_CustomEvent_TriggeringProfileCard) == 0x000110, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_CustomEvent_TriggeringProfileCard' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_CreateDelegate_OutputDelegate_1) == 0x000118, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_CustomEvent_CallingModal_1) == 0x000128, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_CustomEvent_CallingModal_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_CustomEvent_TextEntry) == 0x000130, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_CustomEvent_TextEntry' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_CustomEvent_CallingModal) == 0x000148, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_CustomEvent_CallingModal' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, Temp_int_Loop_Counter_Variable_3) == 0x000150, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::Temp_int_Loop_Counter_Variable_3' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Add_IntInt_ReturnValue_5) == 0x000154, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Add_IntInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_ComponentBoundEvent_ButtonID) == 0x000158, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_ComponentBoundEvent_ButtonID' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_SwitchString_CmpSuccess) == 0x000168, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_SwitchString_CmpSuccess' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_CustomEvent_SelectedProfileCard_1) == 0x000170, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_CustomEvent_SelectedProfileCard_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_CreateDelegate_OutputDelegate_2) == 0x000178, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, Temp_int_Loop_Counter_Variable_4) == 0x000188, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::Temp_int_Loop_Counter_Variable_4' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_IsValid_ReturnValue_2) == 0x00018C, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Add_IntInt_ReturnValue_6) == 0x000190, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Add_IntInt_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_DynamicCast_AsW_Commander_Profile_Card) == 0x000198, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_DynamicCast_AsW_Commander_Profile_Card' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_DynamicCast_bSuccess) == 0x0001A0, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_CustomEvent_SelectedProfileCard) == 0x0001A8, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_CustomEvent_SelectedProfileCard' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Array_Get_Item) == 0x0001B0, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x0001B8, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_BooleanAND_ReturnValue) == 0x0001B9, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_BooleanAND_ReturnValue_1) == 0x0001BA, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_SlotAsHorizontalBoxSlot_ReturnValue) == 0x0001C0, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_SlotAsHorizontalBoxSlot_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Array_Length_ReturnValue) == 0x0001C8, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Less_IntInt_ReturnValue) == 0x0001CC, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_MakeLiteralBool_ReturnValue) == 0x0001CD, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_MakeLiteralBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, Temp_text_Variable_2) == 0x0001D0, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::Temp_text_Variable_2' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, Temp_struct_Variable) == 0x0001E8, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Array_Add_ReturnValue) == 0x0001F8, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_AddChildToHorizontalBox_ReturnValue) == 0x000200, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_AddChildToHorizontalBox_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Array_Get_Item_1) == 0x000208, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Array_Length_ReturnValue_1) == 0x000210, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Less_IntInt_ReturnValue_1) == 0x000214, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_AddChildToHorizontalBox_ReturnValue_1) == 0x000218, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_AddChildToHorizontalBox_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Array_Get_Item_2) == 0x000220, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Array_Get_Item_3) == 0x000228, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Array_Get_Item_3' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Array_Length_ReturnValue_2) == 0x000230, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Array_Length_ReturnValue_3) == 0x000234, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Array_Length_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Less_IntInt_ReturnValue_2) == 0x000238, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Less_IntInt_ReturnValue_3) == 0x000239, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Less_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_MakeStruct_SlateChildSize_1) == 0x00023C, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_MakeStruct_SlateChildSize_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Array_Get_Item_4) == 0x000248, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Array_Get_Item_4' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Array_Get_Item_5) == 0x000250, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Array_Get_Item_5' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_IsValid_ReturnValue_3) == 0x000258, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Array_Get_Item_6) == 0x000260, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Array_Get_Item_6' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Array_Get_Item_7) == 0x000268, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Array_Get_Item_7' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_IsValid_ReturnValue_4) == 0x000270, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Array_Length_ReturnValue_4) == 0x000274, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Array_Length_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Less_IntInt_ReturnValue_4) == 0x000278, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Less_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_CreateDelegate_OutputDelegate_3) == 0x00027C, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Add_IntInt_ReturnValue_7) == 0x00028C, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Add_IntInt_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_CreateDelegate_OutputDelegate_4) == 0x000290, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Conv_IntToInt64_ReturnValue) == 0x0002A0, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Conv_IntToInt64_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_MakeStruct_FormatArgumentData) == 0x0002A8, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_MakeArray_Array) == 0x0002F8, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Format_ReturnValue) == 0x000308, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.FillCardList
// 0x0038 (0x0038 - 0x0000)
struct W_CommanderProfileSelect_C_FillCardList final
{
public:
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateChildSize                        K2Node_MakeStruct_SlateChildSize;                  // 0x0010(0x0008)(NoDestructor)
	class UW_CommanderProfileCard_C*              CallFunc_Array_Get_Item;                           // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UHorizontalBoxSlot*                     CallFunc_AddChildToHorizontalBox_ReturnValue;      // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_1;            // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Max_ReturnValue;                          // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_CommanderProfileSelect_C_FillCardList) == 0x000008, "Wrong alignment on W_CommanderProfileSelect_C_FillCardList");
static_assert(sizeof(W_CommanderProfileSelect_C_FillCardList) == 0x000038, "Wrong size on W_CommanderProfileSelect_C_FillCardList");
static_assert(offsetof(W_CommanderProfileSelect_C_FillCardList, Temp_int_Loop_Counter_Variable) == 0x000000, "Member 'W_CommanderProfileSelect_C_FillCardList::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_FillCardList, CallFunc_Subtract_IntInt_ReturnValue) == 0x000004, "Member 'W_CommanderProfileSelect_C_FillCardList::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_FillCardList, CallFunc_GreaterEqual_IntInt_ReturnValue) == 0x000008, "Member 'W_CommanderProfileSelect_C_FillCardList::CallFunc_GreaterEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_FillCardList, Temp_int_Array_Index_Variable) == 0x00000C, "Member 'W_CommanderProfileSelect_C_FillCardList::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_FillCardList, K2Node_MakeStruct_SlateChildSize) == 0x000010, "Member 'W_CommanderProfileSelect_C_FillCardList::K2Node_MakeStruct_SlateChildSize' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_FillCardList, CallFunc_Array_Get_Item) == 0x000018, "Member 'W_CommanderProfileSelect_C_FillCardList::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_FillCardList, CallFunc_Array_Length_ReturnValue) == 0x000020, "Member 'W_CommanderProfileSelect_C_FillCardList::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_FillCardList, CallFunc_AddChildToHorizontalBox_ReturnValue) == 0x000028, "Member 'W_CommanderProfileSelect_C_FillCardList::CallFunc_AddChildToHorizontalBox_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_FillCardList, CallFunc_Subtract_IntInt_ReturnValue_1) == 0x000030, "Member 'W_CommanderProfileSelect_C_FillCardList::CallFunc_Subtract_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_FillCardList, CallFunc_Max_ReturnValue) == 0x000034, "Member 'W_CommanderProfileSelect_C_FillCardList::CallFunc_Max_ReturnValue' has a wrong offset!");

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.HandleProfileCardSelected
// 0x0008 (0x0008 - 0x0000)
struct W_CommanderProfileSelect_C_HandleProfileCardSelected final
{
public:
	class UW_CommanderProfileCard_C*              SelectedProfileCard;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_CommanderProfileSelect_C_HandleProfileCardSelected) == 0x000008, "Wrong alignment on W_CommanderProfileSelect_C_HandleProfileCardSelected");
static_assert(sizeof(W_CommanderProfileSelect_C_HandleProfileCardSelected) == 0x000008, "Wrong size on W_CommanderProfileSelect_C_HandleProfileCardSelected");
static_assert(offsetof(W_CommanderProfileSelect_C_HandleProfileCardSelected, SelectedProfileCard) == 0x000000, "Member 'W_CommanderProfileSelect_C_HandleProfileCardSelected::SelectedProfileCard' has a wrong offset!");

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.HandleProfileCardUnselected
// 0x0008 (0x0008 - 0x0000)
struct W_CommanderProfileSelect_C_HandleProfileCardUnselected final
{
public:
	class UW_CommanderProfileCard_C*              SelectedProfileCard;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_CommanderProfileSelect_C_HandleProfileCardUnselected) == 0x000008, "Wrong alignment on W_CommanderProfileSelect_C_HandleProfileCardUnselected");
static_assert(sizeof(W_CommanderProfileSelect_C_HandleProfileCardUnselected) == 0x000008, "Wrong size on W_CommanderProfileSelect_C_HandleProfileCardUnselected");
static_assert(offsetof(W_CommanderProfileSelect_C_HandleProfileCardUnselected, SelectedProfileCard) == 0x000000, "Member 'W_CommanderProfileSelect_C_HandleProfileCardUnselected::SelectedProfileCard' has a wrong offset!");

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.OpenDeleteSaveConfirmation
// 0x0008 (0x0008 - 0x0000)
struct W_CommanderProfileSelect_C_OpenDeleteSaveConfirmation final
{
public:
	class UW_CommanderProfileCard_C*              TriggeringProfileCard;                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_CommanderProfileSelect_C_OpenDeleteSaveConfirmation) == 0x000008, "Wrong alignment on W_CommanderProfileSelect_C_OpenDeleteSaveConfirmation");
static_assert(sizeof(W_CommanderProfileSelect_C_OpenDeleteSaveConfirmation) == 0x000008, "Wrong size on W_CommanderProfileSelect_C_OpenDeleteSaveConfirmation");
static_assert(offsetof(W_CommanderProfileSelect_C_OpenDeleteSaveConfirmation, TriggeringProfileCard) == 0x000000, "Member 'W_CommanderProfileSelect_C_OpenDeleteSaveConfirmation::TriggeringProfileCard' has a wrong offset!");

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.Populate Difficulties
// 0x0138 (0x0138 - 0x0000)
struct W_CommanderProfileSelect_C_Populate_Difficulties final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UDifficultySubsystem*                   CallFunc_GetEngineSubsystem_ReturnValue;           // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UW_CommanderProfileCard_C* CommanderProfileCardReference)> K2Node_CreateDelegate_OutputDelegate; // 0x0010(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<struct FGameplayTag>                   CallFunc_GetOrderedDifficulties_ReturnValue;       // 0x0020(0x0010)(ReferenceParm)
	struct FGameplayTag                           CallFunc_Array_Get_Item;                           // 0x0030(0x0008)(NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FDifficultyData                        CallFunc_Map_Find_Value;                           // 0x0040(0x0098)()
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D9[0x3];                                       // 0x00D9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UW_CommanderProfileCard_C* TriggeringProfileCard)> K2Node_CreateDelegate_OutputDelegate_1; // 0x00DC(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x00EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue; // 0x00F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             K2Node_DynamicCast_AsTexture_2D;                   // 0x00F8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0101(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_102[0x2];                                      // 0x0102(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0104(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UW_CommanderProfileCard_C* TriggeringProfileCard, bool Hovered)> K2Node_CreateDelegate_OutputDelegate_2; // 0x0108(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FSlateChildSize                        K2Node_MakeStruct_SlateChildSize;                  // 0x0118(0x0008)(NoDestructor)
	class UW_CommanderProfileCard_C*              CallFunc_Create_ReturnValue;                       // 0x0120(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0128(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12C[0x4];                                      // 0x012C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UHorizontalBoxSlot*                     CallFunc_AddChildToHorizontalBox_ReturnValue;      // 0x0130(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_CommanderProfileSelect_C_Populate_Difficulties) == 0x000008, "Wrong alignment on W_CommanderProfileSelect_C_Populate_Difficulties");
static_assert(sizeof(W_CommanderProfileSelect_C_Populate_Difficulties) == 0x000138, "Wrong size on W_CommanderProfileSelect_C_Populate_Difficulties");
static_assert(offsetof(W_CommanderProfileSelect_C_Populate_Difficulties, Temp_int_Array_Index_Variable) == 0x000000, "Member 'W_CommanderProfileSelect_C_Populate_Difficulties::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_Populate_Difficulties, CallFunc_GetEngineSubsystem_ReturnValue) == 0x000008, "Member 'W_CommanderProfileSelect_C_Populate_Difficulties::CallFunc_GetEngineSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_Populate_Difficulties, K2Node_CreateDelegate_OutputDelegate) == 0x000010, "Member 'W_CommanderProfileSelect_C_Populate_Difficulties::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_Populate_Difficulties, CallFunc_GetOrderedDifficulties_ReturnValue) == 0x000020, "Member 'W_CommanderProfileSelect_C_Populate_Difficulties::CallFunc_GetOrderedDifficulties_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_Populate_Difficulties, CallFunc_Array_Get_Item) == 0x000030, "Member 'W_CommanderProfileSelect_C_Populate_Difficulties::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_Populate_Difficulties, CallFunc_Array_Length_ReturnValue) == 0x000038, "Member 'W_CommanderProfileSelect_C_Populate_Difficulties::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_Populate_Difficulties, CallFunc_Map_Find_Value) == 0x000040, "Member 'W_CommanderProfileSelect_C_Populate_Difficulties::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_Populate_Difficulties, CallFunc_Map_Find_ReturnValue) == 0x0000D8, "Member 'W_CommanderProfileSelect_C_Populate_Difficulties::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_Populate_Difficulties, K2Node_CreateDelegate_OutputDelegate_1) == 0x0000DC, "Member 'W_CommanderProfileSelect_C_Populate_Difficulties::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_Populate_Difficulties, Temp_int_Loop_Counter_Variable) == 0x0000EC, "Member 'W_CommanderProfileSelect_C_Populate_Difficulties::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_Populate_Difficulties, CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue) == 0x0000F0, "Member 'W_CommanderProfileSelect_C_Populate_Difficulties::CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_Populate_Difficulties, K2Node_DynamicCast_AsTexture_2D) == 0x0000F8, "Member 'W_CommanderProfileSelect_C_Populate_Difficulties::K2Node_DynamicCast_AsTexture_2D' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_Populate_Difficulties, K2Node_DynamicCast_bSuccess) == 0x000100, "Member 'W_CommanderProfileSelect_C_Populate_Difficulties::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_Populate_Difficulties, CallFunc_Less_IntInt_ReturnValue) == 0x000101, "Member 'W_CommanderProfileSelect_C_Populate_Difficulties::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_Populate_Difficulties, CallFunc_Add_IntInt_ReturnValue) == 0x000104, "Member 'W_CommanderProfileSelect_C_Populate_Difficulties::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_Populate_Difficulties, K2Node_CreateDelegate_OutputDelegate_2) == 0x000108, "Member 'W_CommanderProfileSelect_C_Populate_Difficulties::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_Populate_Difficulties, K2Node_MakeStruct_SlateChildSize) == 0x000118, "Member 'W_CommanderProfileSelect_C_Populate_Difficulties::K2Node_MakeStruct_SlateChildSize' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_Populate_Difficulties, CallFunc_Create_ReturnValue) == 0x000120, "Member 'W_CommanderProfileSelect_C_Populate_Difficulties::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_Populate_Difficulties, CallFunc_Array_Add_ReturnValue) == 0x000128, "Member 'W_CommanderProfileSelect_C_Populate_Difficulties::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_Populate_Difficulties, CallFunc_AddChildToHorizontalBox_ReturnValue) == 0x000130, "Member 'W_CommanderProfileSelect_C_Populate_Difficulties::CallFunc_AddChildToHorizontalBox_ReturnValue' has a wrong offset!");

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.ProfileHoverStateChange
// 0x0010 (0x0010 - 0x0000)
struct W_CommanderProfileSelect_C_ProfileHoverStateChange final
{
public:
	class UW_CommanderProfileCard_C*              TriggeringProfileCard;                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          Hovered;                                           // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_CommanderProfileSelect_C_ProfileHoverStateChange) == 0x000008, "Wrong alignment on W_CommanderProfileSelect_C_ProfileHoverStateChange");
static_assert(sizeof(W_CommanderProfileSelect_C_ProfileHoverStateChange) == 0x000010, "Wrong size on W_CommanderProfileSelect_C_ProfileHoverStateChange");
static_assert(offsetof(W_CommanderProfileSelect_C_ProfileHoverStateChange, TriggeringProfileCard) == 0x000000, "Member 'W_CommanderProfileSelect_C_ProfileHoverStateChange::TriggeringProfileCard' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ProfileHoverStateChange, Hovered) == 0x000008, "Member 'W_CommanderProfileSelect_C_ProfileHoverStateChange::Hovered' has a wrong offset!");

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.ResetCurrentUnhoverFill
// 0x0018 (0x0018 - 0x0000)
struct W_CommanderProfileSelect_C_ResetCurrentUnhoverFill final
{
public:
	struct FSlateChildSize                        K2Node_MakeStruct_SlateChildSize;                  // 0x0000(0x0008)(NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UHorizontalBoxSlot*                     CallFunc_SlotAsHorizontalBoxSlot_ReturnValue;      // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_CommanderProfileSelect_C_ResetCurrentUnhoverFill) == 0x000008, "Wrong alignment on W_CommanderProfileSelect_C_ResetCurrentUnhoverFill");
static_assert(sizeof(W_CommanderProfileSelect_C_ResetCurrentUnhoverFill) == 0x000018, "Wrong size on W_CommanderProfileSelect_C_ResetCurrentUnhoverFill");
static_assert(offsetof(W_CommanderProfileSelect_C_ResetCurrentUnhoverFill, K2Node_MakeStruct_SlateChildSize) == 0x000000, "Member 'W_CommanderProfileSelect_C_ResetCurrentUnhoverFill::K2Node_MakeStruct_SlateChildSize' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ResetCurrentUnhoverFill, CallFunc_IsValid_ReturnValue) == 0x000008, "Member 'W_CommanderProfileSelect_C_ResetCurrentUnhoverFill::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ResetCurrentUnhoverFill, CallFunc_SlotAsHorizontalBoxSlot_ReturnValue) == 0x000010, "Member 'W_CommanderProfileSelect_C_ResetCurrentUnhoverFill::CallFunc_SlotAsHorizontalBoxSlot_ReturnValue' has a wrong offset!");

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.SetCurrentHoverFill
// 0x0018 (0x0018 - 0x0000)
struct W_CommanderProfileSelect_C_SetCurrentHoverFill final
{
public:
	struct FSlateChildSize                        K2Node_MakeStruct_SlateChildSize;                  // 0x0000(0x0008)(NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UHorizontalBoxSlot*                     CallFunc_SlotAsHorizontalBoxSlot_ReturnValue;      // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_CommanderProfileSelect_C_SetCurrentHoverFill) == 0x000008, "Wrong alignment on W_CommanderProfileSelect_C_SetCurrentHoverFill");
static_assert(sizeof(W_CommanderProfileSelect_C_SetCurrentHoverFill) == 0x000018, "Wrong size on W_CommanderProfileSelect_C_SetCurrentHoverFill");
static_assert(offsetof(W_CommanderProfileSelect_C_SetCurrentHoverFill, K2Node_MakeStruct_SlateChildSize) == 0x000000, "Member 'W_CommanderProfileSelect_C_SetCurrentHoverFill::K2Node_MakeStruct_SlateChildSize' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_SetCurrentHoverFill, CallFunc_IsValid_ReturnValue) == 0x000008, "Member 'W_CommanderProfileSelect_C_SetCurrentHoverFill::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_SetCurrentHoverFill, CallFunc_SlotAsHorizontalBoxSlot_ReturnValue) == 0x000010, "Member 'W_CommanderProfileSelect_C_SetCurrentHoverFill::CallFunc_SlotAsHorizontalBoxSlot_ReturnValue' has a wrong offset!");

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.Tick
// 0x003C (0x003C - 0x0000)
struct W_CommanderProfileSelect_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_CommanderProfileSelect_C_Tick) == 0x000004, "Wrong alignment on W_CommanderProfileSelect_C_Tick");
static_assert(sizeof(W_CommanderProfileSelect_C_Tick) == 0x00003C, "Wrong size on W_CommanderProfileSelect_C_Tick");
static_assert(offsetof(W_CommanderProfileSelect_C_Tick, MyGeometry) == 0x000000, "Member 'W_CommanderProfileSelect_C_Tick::MyGeometry' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_Tick, InDeltaTime) == 0x000038, "Member 'W_CommanderProfileSelect_C_Tick::InDeltaTime' has a wrong offset!");

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.W_CommanderProfileSelect_AutoGenFunc
// 0x0010 (0x0010 - 0x0000)
struct W_CommanderProfileSelect_C_W_CommanderProfileSelect_AutoGenFunc final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          Selected;                                          // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_CommanderProfileSelect_C_W_CommanderProfileSelect_AutoGenFunc) == 0x000008, "Wrong alignment on W_CommanderProfileSelect_C_W_CommanderProfileSelect_AutoGenFunc");
static_assert(sizeof(W_CommanderProfileSelect_C_W_CommanderProfileSelect_AutoGenFunc) == 0x000010, "Wrong size on W_CommanderProfileSelect_C_W_CommanderProfileSelect_AutoGenFunc");
static_assert(offsetof(W_CommanderProfileSelect_C_W_CommanderProfileSelect_AutoGenFunc, Button) == 0x000000, "Member 'W_CommanderProfileSelect_C_W_CommanderProfileSelect_AutoGenFunc::Button' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_W_CommanderProfileSelect_AutoGenFunc, Selected) == 0x000008, "Member 'W_CommanderProfileSelect_C_W_CommanderProfileSelect_AutoGenFunc::Selected' has a wrong offset!");

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.BP_GetDesiredFocusTarget
// 0x0010 (0x0010 - 0x0000)
struct W_CommanderProfileSelect_C_BP_GetDesiredFocusTarget final
{
public:
	class UWidget*                                ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UW_CommanderProfileCard_C*              CallFunc_Array_Get_Item;                           // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_CommanderProfileSelect_C_BP_GetDesiredFocusTarget) == 0x000008, "Wrong alignment on W_CommanderProfileSelect_C_BP_GetDesiredFocusTarget");
static_assert(sizeof(W_CommanderProfileSelect_C_BP_GetDesiredFocusTarget) == 0x000010, "Wrong size on W_CommanderProfileSelect_C_BP_GetDesiredFocusTarget");
static_assert(offsetof(W_CommanderProfileSelect_C_BP_GetDesiredFocusTarget, ReturnValue) == 0x000000, "Member 'W_CommanderProfileSelect_C_BP_GetDesiredFocusTarget::ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_BP_GetDesiredFocusTarget, CallFunc_Array_Get_Item) == 0x000008, "Member 'W_CommanderProfileSelect_C_BP_GetDesiredFocusTarget::CallFunc_Array_Get_Item' has a wrong offset!");

}

