#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_GammaSetting

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_GammaSetting.W_GammaSetting_C
// 0x0018 (0x0430 - 0x0418)
class UW_GammaSetting_C final : public UGammaSetting
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0418(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UAnalogSlider*                          AnalogSlider_57;                                   // 0x0420(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UProgressBar*                           ProgressBar;                                       // 0x0428(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void BndEvt__W_GammaSetting_AnalogSlider_57_K2Node_ComponentBoundEvent_0_OnFloatValueChangedEvent__DelegateSignature(float Value);
	void Construct();
	void DoCustomNavigation(EUINavigation Navigation_0);
	void ExecuteUbergraph_W_GammaSetting(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_GammaSetting_C">();
	}
	static class UW_GammaSetting_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_GammaSetting_C>();
	}
};
static_assert(alignof(UW_GammaSetting_C) == 0x000008, "Wrong alignment on UW_GammaSetting_C");
static_assert(sizeof(UW_GammaSetting_C) == 0x000430, "Wrong size on UW_GammaSetting_C");
static_assert(offsetof(UW_GammaSetting_C, UberGraphFrame) == 0x000418, "Member 'UW_GammaSetting_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UW_GammaSetting_C, AnalogSlider_57) == 0x000420, "Member 'UW_GammaSetting_C::AnalogSlider_57' has a wrong offset!");
static_assert(offsetof(UW_GammaSetting_C, ProgressBar) == 0x000428, "Member 'UW_GammaSetting_C::ProgressBar' has a wrong offset!");

}

