#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_PlayersList_Entry

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ReadyOrNot_structs.hpp"
#include "OnlineSubsystemUtils_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_PlayersList_Entry.W_PlayersList_Entry_C
// 0x02C0 (0x0580 - 0x02C0)
class UW_PlayersList_Entry_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Avatar;                                            // 0x02C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonButton_C*                        BaseButton;                                        // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_Button_C*                            BlockButton;                                       // 0x02D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_InputActionButton_C*                 BlockButtonGamepad;                                // 0x02E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HB_GamepadBlock;                                   // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HB_GamepadButtons;                                 // 0x02F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HB_GamepadKick;                                    // 0x02F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HB_GamepadMute;                                    // 0x0300(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HB_GamepadReport;                                  // 0x0308(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HB_MKBButtons;                                     // 0x0310(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       HostText;                                          // 0x0318(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_Button_C*                            KickButton;                                        // 0x0320(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_InputActionButton_C*                 KickButtonGamepad;                                 // 0x0328(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_Button_C*                            MuteButton;                                        // 0x0330(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_InputActionButton_C*                 MuteButtonGamepad;                                 // 0x0338(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 MuteIcon;                                          // 0x0340(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlay;                                           // 0x0348(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlay_0;                                         // 0x0350(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 PlatformIcon;                                      // 0x0358(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       PlayerName;                                        // 0x0360(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_Button_C*                            ReportButton;                                      // 0x0368(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_InputActionButton_C*                 ReportButtonGamepad;                               // 0x0370(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Status;                                            // 0x0378(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VerticalBox_1;                                     // 0x0380(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_Button_C*                            ViewProfileButton;                                 // 0x0388(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_InputActionButton_C*                 ViewProfileButtonGamepad;                          // 0x0390(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FLobbyPlayer                           Player;                                            // 0x0398(0x0070)(Edit, BlueprintVisible, ExposeOnSpawn)
	bool                                          bFoundLobby;                                       // 0x0408(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_409[0x7];                                      // 0x0409(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBlueprintSessionResult                PlayerSession;                                     // 0x0410(0x0120)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   StatusText;                                        // 0x0530(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class AReadyOrNotGameMode*>            Modes;                                             // 0x0548(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	class UClass*                                 PlayingMode;                                       // 0x0558(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UW_PlayersList_C*                       PlayersList;                                       // 0x0560(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsBlockButtonVisible;                             // 0x0568(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_569[0x7];                                      // 0x0569(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 ReportMessage;                                     // 0x0570(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)

public:
	void bLock(class UW_StandardModal_C* CallingModal, const class FText& TextEntry);
	void Block_and_Report_Player(class UW_ReportModal_C* CallingModal, const class FText& TextEntry);
	void BndEvt__W_PlayersList_Entry_BaseButton_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_BaseButton_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_BlockButton_K2Node_ComponentBoundEvent_16_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_BlockButton_K2Node_ComponentBoundEvent_30_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_BlockButton_K2Node_ComponentBoundEvent_4_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_BlockButtonGamepad_K2Node_ComponentBoundEvent_24_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_BlockButtonGamepad_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_CommonButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_KickButton_K2Node_ComponentBoundEvent_15_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_KickButton_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_KickButton_K2Node_ComponentBoundEvent_29_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_KickButtonGamepad_K2Node_ComponentBoundEvent_14_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_KickButtonGamepad_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_MuteButton_K2Node_ComponentBoundEvent_18_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_MuteButton_K2Node_ComponentBoundEvent_28_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_MuteButtonGamepad_K2Node_ComponentBoundEvent_13_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_MuteButtonGamepad_K2Node_ComponentBoundEvent_27_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_MuteButtonGamepad_K2Node_ComponentBoundEvent_9_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_ReportButton_K2Node_ComponentBoundEvent_11_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_ReportButton_K2Node_ComponentBoundEvent_19_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_ReportButton_K2Node_ComponentBoundEvent_31_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_ReportButtonGamepad_K2Node_ComponentBoundEvent_25_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_ReportButtonGamepad_K2Node_ComponentBoundEvent_7_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_ViewProfileButton_K2Node_ComponentBoundEvent_12_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_ViewProfileButton_K2Node_ComponentBoundEvent_17_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_ViewProfileButton_K2Node_ComponentBoundEvent_32_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_ViewProfileButtonGamepad_K2Node_ComponentBoundEvent_26_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_ViewProfileButtonGamepad_K2Node_ComponentBoundEvent_8_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_W_InputActionButton_K2Node_ComponentBoundEvent_20_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_W_InputActionButton_K2Node_ComponentBoundEvent_21_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_W_InputActionButton_K2Node_ComponentBoundEvent_22_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_PlayersList_Entry_W_InputActionButton_K2Node_ComponentBoundEvent_23_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void Cancel_kick(class UStandardModal* CallingModal);
	void CancelBlock(class UStandardModal* CallingModal);
	void CancelReport(class UStandardModal* CallingModal);
	void Construct();
	void ExecuteUbergraph_W_PlayersList_Entry(int32 EntryPoint);
	struct FSlateColor GetColorAndOpacity_0();
	void Initialise_Popup(const struct FLobbyPlayer& Player_Name, const class FText& TextFormat, const class FText& ButtonText, bool Show_Cancel_Button, class UW_StandardModal_C** OutputPopUp);
	void kick(class UW_StandardModal_C* CallingModal, const class FText& TextEntry);
	void OK_Clicked();
	void OnImageFetched(class UTexture2D* InTexture);
	void RefreshOnlinePlatformType(int32 OnlinePlatformType);
	void RefreshPlayer(const struct FLobbyPlayer& Player_0);
	void Report_Player(class UW_ReportModal_C* CallingModal, const class FText& TextEntry);
	void ReportCompleted(bool WasReportSuccessful);
	void SetProfileButtonVisibility();
	void UpdatePlatformIcon();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_PlayersList_Entry_C">();
	}
	static class UW_PlayersList_Entry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_PlayersList_Entry_C>();
	}
};
static_assert(alignof(UW_PlayersList_Entry_C) == 0x000008, "Wrong alignment on UW_PlayersList_Entry_C");
static_assert(sizeof(UW_PlayersList_Entry_C) == 0x000580, "Wrong size on UW_PlayersList_Entry_C");
static_assert(offsetof(UW_PlayersList_Entry_C, UberGraphFrame) == 0x0002C0, "Member 'UW_PlayersList_Entry_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, Avatar) == 0x0002C8, "Member 'UW_PlayersList_Entry_C::Avatar' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, BaseButton) == 0x0002D0, "Member 'UW_PlayersList_Entry_C::BaseButton' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, BlockButton) == 0x0002D8, "Member 'UW_PlayersList_Entry_C::BlockButton' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, BlockButtonGamepad) == 0x0002E0, "Member 'UW_PlayersList_Entry_C::BlockButtonGamepad' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, HB_GamepadBlock) == 0x0002E8, "Member 'UW_PlayersList_Entry_C::HB_GamepadBlock' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, HB_GamepadButtons) == 0x0002F0, "Member 'UW_PlayersList_Entry_C::HB_GamepadButtons' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, HB_GamepadKick) == 0x0002F8, "Member 'UW_PlayersList_Entry_C::HB_GamepadKick' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, HB_GamepadMute) == 0x000300, "Member 'UW_PlayersList_Entry_C::HB_GamepadMute' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, HB_GamepadReport) == 0x000308, "Member 'UW_PlayersList_Entry_C::HB_GamepadReport' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, HB_MKBButtons) == 0x000310, "Member 'UW_PlayersList_Entry_C::HB_MKBButtons' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, HostText) == 0x000318, "Member 'UW_PlayersList_Entry_C::HostText' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, KickButton) == 0x000320, "Member 'UW_PlayersList_Entry_C::KickButton' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, KickButtonGamepad) == 0x000328, "Member 'UW_PlayersList_Entry_C::KickButtonGamepad' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, MuteButton) == 0x000330, "Member 'UW_PlayersList_Entry_C::MuteButton' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, MuteButtonGamepad) == 0x000338, "Member 'UW_PlayersList_Entry_C::MuteButtonGamepad' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, MuteIcon) == 0x000340, "Member 'UW_PlayersList_Entry_C::MuteIcon' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, Overlay) == 0x000348, "Member 'UW_PlayersList_Entry_C::Overlay' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, Overlay_0) == 0x000350, "Member 'UW_PlayersList_Entry_C::Overlay_0' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, PlatformIcon) == 0x000358, "Member 'UW_PlayersList_Entry_C::PlatformIcon' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, PlayerName) == 0x000360, "Member 'UW_PlayersList_Entry_C::PlayerName' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, ReportButton) == 0x000368, "Member 'UW_PlayersList_Entry_C::ReportButton' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, ReportButtonGamepad) == 0x000370, "Member 'UW_PlayersList_Entry_C::ReportButtonGamepad' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, Status) == 0x000378, "Member 'UW_PlayersList_Entry_C::Status' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, VerticalBox_1) == 0x000380, "Member 'UW_PlayersList_Entry_C::VerticalBox_1' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, ViewProfileButton) == 0x000388, "Member 'UW_PlayersList_Entry_C::ViewProfileButton' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, ViewProfileButtonGamepad) == 0x000390, "Member 'UW_PlayersList_Entry_C::ViewProfileButtonGamepad' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, Player) == 0x000398, "Member 'UW_PlayersList_Entry_C::Player' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, bFoundLobby) == 0x000408, "Member 'UW_PlayersList_Entry_C::bFoundLobby' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, PlayerSession) == 0x000410, "Member 'UW_PlayersList_Entry_C::PlayerSession' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, StatusText) == 0x000530, "Member 'UW_PlayersList_Entry_C::StatusText' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, Modes) == 0x000548, "Member 'UW_PlayersList_Entry_C::Modes' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, PlayingMode) == 0x000558, "Member 'UW_PlayersList_Entry_C::PlayingMode' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, PlayersList) == 0x000560, "Member 'UW_PlayersList_Entry_C::PlayersList' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, bIsBlockButtonVisible) == 0x000568, "Member 'UW_PlayersList_Entry_C::bIsBlockButtonVisible' has a wrong offset!");
static_assert(offsetof(UW_PlayersList_Entry_C, ReportMessage) == 0x000570, "Member 'UW_PlayersList_Entry_C::ReportMessage' has a wrong offset!");

}

