#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Premission_Tablet_Overlay

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "CommonInput_structs.hpp"


namespace SDK::Params
{

// Function W_Premission_Tablet_Overlay.W_Premission_Tablet_Overlay_C.ExecuteUbergraph_W_Premission_Tablet_Overlay
// 0x0028 (0x0028 - 0x0000)
struct W_Premission_Tablet_Overlay_C_ExecuteUbergraph_W_Premission_Tablet_Overlay final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(ECommonInputType bNewInputType)> K2Node_CreateDelegate_OutputDelegate;            // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonInputSubsystem*                  CallFunc_GetLocalPlayerSubsystem_ReturnValue;      // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	ECommonInputType                              CallFunc_GetCurrentInputType_ReturnValue;          // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_Premission_Tablet_Overlay_C_ExecuteUbergraph_W_Premission_Tablet_Overlay) == 0x000008, "Wrong alignment on W_Premission_Tablet_Overlay_C_ExecuteUbergraph_W_Premission_Tablet_Overlay");
static_assert(sizeof(W_Premission_Tablet_Overlay_C_ExecuteUbergraph_W_Premission_Tablet_Overlay) == 0x000028, "Wrong size on W_Premission_Tablet_Overlay_C_ExecuteUbergraph_W_Premission_Tablet_Overlay");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_ExecuteUbergraph_W_Premission_Tablet_Overlay, EntryPoint) == 0x000000, "Member 'W_Premission_Tablet_Overlay_C_ExecuteUbergraph_W_Premission_Tablet_Overlay::EntryPoint' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_ExecuteUbergraph_W_Premission_Tablet_Overlay, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'W_Premission_Tablet_Overlay_C_ExecuteUbergraph_W_Premission_Tablet_Overlay::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_ExecuteUbergraph_W_Premission_Tablet_Overlay, CallFunc_GetLocalPlayerSubsystem_ReturnValue) == 0x000018, "Member 'W_Premission_Tablet_Overlay_C_ExecuteUbergraph_W_Premission_Tablet_Overlay::CallFunc_GetLocalPlayerSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_ExecuteUbergraph_W_Premission_Tablet_Overlay, CallFunc_GetCurrentInputType_ReturnValue) == 0x000020, "Member 'W_Premission_Tablet_Overlay_C_ExecuteUbergraph_W_Premission_Tablet_Overlay::CallFunc_GetCurrentInputType_ReturnValue' has a wrong offset!");

// Function W_Premission_Tablet_Overlay.W_Premission_Tablet_Overlay_C.HandleInputChange
// 0x0001 (0x0001 - 0x0000)
struct W_Premission_Tablet_Overlay_C_HandleInputChange final
{
public:
	ECommonInputType                              bNewInputType;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_Premission_Tablet_Overlay_C_HandleInputChange) == 0x000001, "Wrong alignment on W_Premission_Tablet_Overlay_C_HandleInputChange");
static_assert(sizeof(W_Premission_Tablet_Overlay_C_HandleInputChange) == 0x000001, "Wrong size on W_Premission_Tablet_Overlay_C_HandleInputChange");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_HandleInputChange, bNewInputType) == 0x000000, "Member 'W_Premission_Tablet_Overlay_C_HandleInputChange::bNewInputType' has a wrong offset!");

// Function W_Premission_Tablet_Overlay.W_Premission_Tablet_Overlay_C.ScreenChange
// 0x0005 (0x0005 - 0x0000)
struct W_Premission_Tablet_Overlay_C_ScreenChange final
{
public:
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_1;    // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_2;    // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_3;    // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_Premission_Tablet_Overlay_C_ScreenChange) == 0x000001, "Wrong alignment on W_Premission_Tablet_Overlay_C_ScreenChange");
static_assert(sizeof(W_Premission_Tablet_Overlay_C_ScreenChange) == 0x000005, "Wrong size on W_Premission_Tablet_Overlay_C_ScreenChange");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_ScreenChange, CallFunc_IsValid_ReturnValue) == 0x000000, "Member 'W_Premission_Tablet_Overlay_C_ScreenChange::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_ScreenChange, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000001, "Member 'W_Premission_Tablet_Overlay_C_ScreenChange::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_ScreenChange, CallFunc_EqualEqual_ObjectObject_ReturnValue_1) == 0x000002, "Member 'W_Premission_Tablet_Overlay_C_ScreenChange::CallFunc_EqualEqual_ObjectObject_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_ScreenChange, CallFunc_EqualEqual_ObjectObject_ReturnValue_2) == 0x000003, "Member 'W_Premission_Tablet_Overlay_C_ScreenChange::CallFunc_EqualEqual_ObjectObject_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_ScreenChange, CallFunc_EqualEqual_ObjectObject_ReturnValue_3) == 0x000004, "Member 'W_Premission_Tablet_Overlay_C_ScreenChange::CallFunc_EqualEqual_ObjectObject_ReturnValue_3' has a wrong offset!");

// Function W_Premission_Tablet_Overlay.W_Premission_Tablet_Overlay_C.SetChatFooterVisibility
// 0x0001 (0x0001 - 0x0000)
struct W_Premission_Tablet_Overlay_C_SetChatFooterVisibility final
{
public:
	bool                                          bIsChatVisible;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_Premission_Tablet_Overlay_C_SetChatFooterVisibility) == 0x000001, "Wrong alignment on W_Premission_Tablet_Overlay_C_SetChatFooterVisibility");
static_assert(sizeof(W_Premission_Tablet_Overlay_C_SetChatFooterVisibility) == 0x000001, "Wrong size on W_Premission_Tablet_Overlay_C_SetChatFooterVisibility");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_SetChatFooterVisibility, bIsChatVisible) == 0x000000, "Member 'W_Premission_Tablet_Overlay_C_SetChatFooterVisibility::bIsChatVisible' has a wrong offset!");

// Function W_Premission_Tablet_Overlay.W_Premission_Tablet_Overlay_C.SetVisibilityFromBool
// 0x0010 (0x0010 - 0x0000)
struct W_Premission_Tablet_Overlay_C_SetVisibilityFromBool final
{
public:
	class UCommonUserWidget*                      Widget;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          Bool;                                              // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              VisibilityIfTrue;                                  // 0x0009(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              VisibilityIfFalse;                                 // 0x000A(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          SameBool;                                          // 0x000B(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_Premission_Tablet_Overlay_C_SetVisibilityFromBool) == 0x000008, "Wrong alignment on W_Premission_Tablet_Overlay_C_SetVisibilityFromBool");
static_assert(sizeof(W_Premission_Tablet_Overlay_C_SetVisibilityFromBool) == 0x000010, "Wrong size on W_Premission_Tablet_Overlay_C_SetVisibilityFromBool");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_SetVisibilityFromBool, Widget) == 0x000000, "Member 'W_Premission_Tablet_Overlay_C_SetVisibilityFromBool::Widget' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_SetVisibilityFromBool, Bool) == 0x000008, "Member 'W_Premission_Tablet_Overlay_C_SetVisibilityFromBool::Bool' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_SetVisibilityFromBool, VisibilityIfTrue) == 0x000009, "Member 'W_Premission_Tablet_Overlay_C_SetVisibilityFromBool::VisibilityIfTrue' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_SetVisibilityFromBool, VisibilityIfFalse) == 0x00000A, "Member 'W_Premission_Tablet_Overlay_C_SetVisibilityFromBool::VisibilityIfFalse' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_SetVisibilityFromBool, SameBool) == 0x00000B, "Member 'W_Premission_Tablet_Overlay_C_SetVisibilityFromBool::SameBool' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_SetVisibilityFromBool, CallFunc_IsValid_ReturnValue) == 0x00000C, "Member 'W_Premission_Tablet_Overlay_C_SetVisibilityFromBool::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function W_Premission_Tablet_Overlay.W_Premission_Tablet_Overlay_C.SubscribeToTabletEvents
// 0x0038 (0x0038 - 0x0000)
struct W_Premission_Tablet_Overlay_C_SubscribeToTabletEvents final
{
public:
	class UW_PreMission_Tablet_C*                 Tablet;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0018(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x0028(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_Premission_Tablet_Overlay_C_SubscribeToTabletEvents) == 0x000008, "Wrong alignment on W_Premission_Tablet_Overlay_C_SubscribeToTabletEvents");
static_assert(sizeof(W_Premission_Tablet_Overlay_C_SubscribeToTabletEvents) == 0x000038, "Wrong size on W_Premission_Tablet_Overlay_C_SubscribeToTabletEvents");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_SubscribeToTabletEvents, Tablet) == 0x000000, "Member 'W_Premission_Tablet_Overlay_C_SubscribeToTabletEvents::Tablet' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_SubscribeToTabletEvents, K2Node_CreateDelegate_OutputDelegate) == 0x000008, "Member 'W_Premission_Tablet_Overlay_C_SubscribeToTabletEvents::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_SubscribeToTabletEvents, K2Node_CreateDelegate_OutputDelegate_1) == 0x000018, "Member 'W_Premission_Tablet_Overlay_C_SubscribeToTabletEvents::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_SubscribeToTabletEvents, K2Node_CreateDelegate_OutputDelegate_2) == 0x000028, "Member 'W_Premission_Tablet_Overlay_C_SubscribeToTabletEvents::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");

// Function W_Premission_Tablet_Overlay.W_Premission_Tablet_Overlay_C.Update Brief Buttons
// 0x00C0 (0x00C0 - 0x0000)
struct W_Premission_Tablet_Overlay_C_Update_Brief_Buttons final
{
public:
	bool                                          IsPlaying;                                         // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Temp_string_Variable;                              // 0x0008(0x0010)(ConstParm, ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Temp_string_Variable_1;                            // 0x0020(0x0010)(ConstParm, ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_Is_on_Audio_Page_OnAudioPage;             // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasEnabledMediaPlayer_MediaPlayerEnabled; // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_32[0x6];                                       // 0x0032(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Temp_string_Variable_2;                            // 0x0038(0x0010)(ConstParm, ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Temp_string_Variable_3;                            // 0x0050(0x0010)(ConstParm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Temp_string_Variable_4;                            // 0x0060(0x0010)(ConstParm, ZeroConstructor, HasGetValueTypeHash)
	class UW_ScreenFooterEntry_C*                 CallFunc_Map_Find_Value;                           // 0x0070(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsAudioPlaying_IsPlaying;                 // 0x0079(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7A[0x6];                                       // 0x007A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_ScreenFooterEntry_C*                 CallFunc_Map_Find_Value_1;                         // 0x0080(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_1;                   // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetVisibilityFromBool_SameBool;           // 0x0089(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetVisibilityFromBool_SameBool_1;         // 0x008A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8B[0x5];                                       // 0x008B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_ScreenFooterEntry_C*                 CallFunc_Map_Find_Value_2;                         // 0x0090(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_2;                   // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_99[0x7];                                       // 0x0099(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_ScreenFooterEntry_C*                 CallFunc_Map_Find_Value_3;                         // 0x00A0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_3;                   // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetVisibilityFromBool_SameBool_2;         // 0x00A9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetVisibilityFromBool_SameBool_3;         // 0x00AA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_AB[0x5];                                       // 0x00AB(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_ScreenFooterEntry_C*                 CallFunc_Map_Find_Value_4;                         // 0x00B0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_4;                   // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetVisibilityFromBool_SameBool_4;         // 0x00B9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons) == 0x000008, "Wrong alignment on W_Premission_Tablet_Overlay_C_Update_Brief_Buttons");
static_assert(sizeof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons) == 0x0000C0, "Wrong size on W_Premission_Tablet_Overlay_C_Update_Brief_Buttons");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons, IsPlaying) == 0x000000, "Member 'W_Premission_Tablet_Overlay_C_Update_Brief_Buttons::IsPlaying' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons, Temp_string_Variable) == 0x000008, "Member 'W_Premission_Tablet_Overlay_C_Update_Brief_Buttons::Temp_string_Variable' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons, CallFunc_IsValid_ReturnValue) == 0x000018, "Member 'W_Premission_Tablet_Overlay_C_Update_Brief_Buttons::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons, Temp_string_Variable_1) == 0x000020, "Member 'W_Premission_Tablet_Overlay_C_Update_Brief_Buttons::Temp_string_Variable_1' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons, CallFunc_Is_on_Audio_Page_OnAudioPage) == 0x000030, "Member 'W_Premission_Tablet_Overlay_C_Update_Brief_Buttons::CallFunc_Is_on_Audio_Page_OnAudioPage' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons, CallFunc_HasEnabledMediaPlayer_MediaPlayerEnabled) == 0x000031, "Member 'W_Premission_Tablet_Overlay_C_Update_Brief_Buttons::CallFunc_HasEnabledMediaPlayer_MediaPlayerEnabled' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons, Temp_string_Variable_2) == 0x000038, "Member 'W_Premission_Tablet_Overlay_C_Update_Brief_Buttons::Temp_string_Variable_2' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons, CallFunc_BooleanAND_ReturnValue) == 0x000048, "Member 'W_Premission_Tablet_Overlay_C_Update_Brief_Buttons::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons, Temp_string_Variable_3) == 0x000050, "Member 'W_Premission_Tablet_Overlay_C_Update_Brief_Buttons::Temp_string_Variable_3' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons, Temp_string_Variable_4) == 0x000060, "Member 'W_Premission_Tablet_Overlay_C_Update_Brief_Buttons::Temp_string_Variable_4' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons, CallFunc_Map_Find_Value) == 0x000070, "Member 'W_Premission_Tablet_Overlay_C_Update_Brief_Buttons::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons, CallFunc_Map_Find_ReturnValue) == 0x000078, "Member 'W_Premission_Tablet_Overlay_C_Update_Brief_Buttons::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons, CallFunc_IsAudioPlaying_IsPlaying) == 0x000079, "Member 'W_Premission_Tablet_Overlay_C_Update_Brief_Buttons::CallFunc_IsAudioPlaying_IsPlaying' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons, CallFunc_Map_Find_Value_1) == 0x000080, "Member 'W_Premission_Tablet_Overlay_C_Update_Brief_Buttons::CallFunc_Map_Find_Value_1' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons, CallFunc_Map_Find_ReturnValue_1) == 0x000088, "Member 'W_Premission_Tablet_Overlay_C_Update_Brief_Buttons::CallFunc_Map_Find_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons, CallFunc_SetVisibilityFromBool_SameBool) == 0x000089, "Member 'W_Premission_Tablet_Overlay_C_Update_Brief_Buttons::CallFunc_SetVisibilityFromBool_SameBool' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons, CallFunc_SetVisibilityFromBool_SameBool_1) == 0x00008A, "Member 'W_Premission_Tablet_Overlay_C_Update_Brief_Buttons::CallFunc_SetVisibilityFromBool_SameBool_1' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons, CallFunc_Map_Find_Value_2) == 0x000090, "Member 'W_Premission_Tablet_Overlay_C_Update_Brief_Buttons::CallFunc_Map_Find_Value_2' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons, CallFunc_Map_Find_ReturnValue_2) == 0x000098, "Member 'W_Premission_Tablet_Overlay_C_Update_Brief_Buttons::CallFunc_Map_Find_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons, CallFunc_Map_Find_Value_3) == 0x0000A0, "Member 'W_Premission_Tablet_Overlay_C_Update_Brief_Buttons::CallFunc_Map_Find_Value_3' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons, CallFunc_Map_Find_ReturnValue_3) == 0x0000A8, "Member 'W_Premission_Tablet_Overlay_C_Update_Brief_Buttons::CallFunc_Map_Find_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons, CallFunc_SetVisibilityFromBool_SameBool_2) == 0x0000A9, "Member 'W_Premission_Tablet_Overlay_C_Update_Brief_Buttons::CallFunc_SetVisibilityFromBool_SameBool_2' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons, CallFunc_SetVisibilityFromBool_SameBool_3) == 0x0000AA, "Member 'W_Premission_Tablet_Overlay_C_Update_Brief_Buttons::CallFunc_SetVisibilityFromBool_SameBool_3' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons, CallFunc_Map_Find_Value_4) == 0x0000B0, "Member 'W_Premission_Tablet_Overlay_C_Update_Brief_Buttons::CallFunc_Map_Find_Value_4' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons, CallFunc_Map_Find_ReturnValue_4) == 0x0000B8, "Member 'W_Premission_Tablet_Overlay_C_Update_Brief_Buttons::CallFunc_Map_Find_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Brief_Buttons, CallFunc_SetVisibilityFromBool_SameBool_4) == 0x0000B9, "Member 'W_Premission_Tablet_Overlay_C_Update_Brief_Buttons::CallFunc_SetVisibilityFromBool_SameBool_4' has a wrong offset!");

// Function W_Premission_Tablet_Overlay.W_Premission_Tablet_Overlay_C.Update Map Buttons
// 0x0158 (0x0158 - 0x0000)
struct W_Premission_Tablet_Overlay_C_Update_Map_Buttons final
{
public:
	bool                                          NewLocalVar;                                       // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsHoveringDeletable;                               // 0x0001(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          LegendIsOpen;                                      // 0x0002(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsNotDrawingOrPlacingOrHovering;                   // 0x0003(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsPlacingIcon;                                     // 0x0004(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsDrawing;                                         // 0x0005(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Temp_string_Variable;                              // 0x0008(0x0010)(ConstParm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Temp_string_Variable_1;                            // 0x0018(0x0010)(ConstParm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Temp_string_Variable_2;                            // 0x0028(0x0010)(ConstParm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Temp_string_Variable_3;                            // 0x0038(0x0010)(ConstParm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Temp_string_Variable_4;                            // 0x0048(0x0010)(ConstParm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Temp_string_Variable_5;                            // 0x0058(0x0010)(ConstParm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Temp_string_Variable_6;                            // 0x0068(0x0010)(ConstParm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Temp_string_Variable_7;                            // 0x0078(0x0010)(ConstParm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Temp_string_Variable_8;                            // 0x0088(0x0010)(ConstParm, ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsMultiplayer_ReturnValue;                // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0099(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x009A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_1;                  // 0x009B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x009C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x009D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9E[0x2];                                       // 0x009E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Temp_string_Variable_9;                            // 0x00A0(0x0010)(ConstParm, ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_2;                  // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x00B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B2[0x6];                                       // 0x00B2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_ScreenFooterEntry_C*                 CallFunc_Map_Find_Value;                           // 0x00B8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C1[0x7];                                       // 0x00C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_ScreenFooterEntry_C*                 CallFunc_Map_Find_Value_1;                         // 0x00C8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_1;                   // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D1[0x7];                                       // 0x00D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_ScreenFooterEntry_C*                 CallFunc_Map_Find_Value_2;                         // 0x00D8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_2;                   // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetVisibilityFromBool_SameBool;           // 0x00E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetVisibilityFromBool_SameBool_1;         // 0x00E2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E3[0x5];                                       // 0x00E3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_ScreenFooterEntry_C*                 CallFunc_Map_Find_Value_3;                         // 0x00E8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_3;                   // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F1[0x7];                                       // 0x00F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_ScreenFooterEntry_C*                 CallFunc_Map_Find_Value_4;                         // 0x00F8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_4;                   // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_101[0x7];                                      // 0x0101(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_ScreenFooterEntry_C*                 CallFunc_Map_Find_Value_5;                         // 0x0108(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_5;                   // 0x0110(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetVisibilityFromBool_SameBool_2;         // 0x0111(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetVisibilityFromBool_SameBool_3;         // 0x0112(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetVisibilityFromBool_SameBool_4;         // 0x0113(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_114[0x4];                                      // 0x0114(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_ScreenFooterEntry_C*                 CallFunc_Map_Find_Value_6;                         // 0x0118(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_6;                   // 0x0120(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_121[0x7];                                      // 0x0121(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_ScreenFooterEntry_C*                 CallFunc_Map_Find_Value_7;                         // 0x0128(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_7;                   // 0x0130(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetVisibilityFromBool_SameBool_5;         // 0x0131(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_132[0x6];                                      // 0x0132(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_ScreenFooterEntry_C*                 CallFunc_Map_Find_Value_8;                         // 0x0138(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_8;                   // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetVisibilityFromBool_SameBool_6;         // 0x0141(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetVisibilityFromBool_SameBool_7;         // 0x0142(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetVisibilityFromBool_SameBool_8;         // 0x0143(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0144(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_145[0x3];                                      // 0x0145(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_ScreenFooterEntry_C*                 CallFunc_Map_Find_Value_9;                         // 0x0148(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_9;                   // 0x0150(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetVisibilityFromBool_SameBool_9;         // 0x0151(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0152(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsGamepadCrosshairHovering_Hovering;      // 0x0153(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons) == 0x000008, "Wrong alignment on W_Premission_Tablet_Overlay_C_Update_Map_Buttons");
static_assert(sizeof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons) == 0x000158, "Wrong size on W_Premission_Tablet_Overlay_C_Update_Map_Buttons");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, NewLocalVar) == 0x000000, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::NewLocalVar' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, IsHoveringDeletable) == 0x000001, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::IsHoveringDeletable' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, LegendIsOpen) == 0x000002, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::LegendIsOpen' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, IsNotDrawingOrPlacingOrHovering) == 0x000003, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::IsNotDrawingOrPlacingOrHovering' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, IsPlacingIcon) == 0x000004, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::IsPlacingIcon' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, IsDrawing) == 0x000005, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::IsDrawing' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, Temp_string_Variable) == 0x000008, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::Temp_string_Variable' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, Temp_string_Variable_1) == 0x000018, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::Temp_string_Variable_1' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, Temp_string_Variable_2) == 0x000028, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::Temp_string_Variable_2' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, Temp_string_Variable_3) == 0x000038, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::Temp_string_Variable_3' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, Temp_string_Variable_4) == 0x000048, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::Temp_string_Variable_4' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, Temp_string_Variable_5) == 0x000058, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::Temp_string_Variable_5' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, Temp_string_Variable_6) == 0x000068, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::Temp_string_Variable_6' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, Temp_string_Variable_7) == 0x000078, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::Temp_string_Variable_7' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, Temp_string_Variable_8) == 0x000088, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::Temp_string_Variable_8' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_IsMultiplayer_ReturnValue) == 0x000098, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_IsMultiplayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_BooleanOR_ReturnValue) == 0x000099, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_BooleanAND_ReturnValue) == 0x00009A, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_BooleanOR_ReturnValue_1) == 0x00009B, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_BooleanOR_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_Not_PreBool_ReturnValue) == 0x00009C, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_BooleanAND_ReturnValue_1) == 0x00009D, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, Temp_string_Variable_9) == 0x0000A0, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::Temp_string_Variable_9' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_BooleanOR_ReturnValue_2) == 0x0000B0, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_BooleanOR_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_Not_PreBool_ReturnValue_1) == 0x0000B1, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_Map_Find_Value) == 0x0000B8, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_Map_Find_ReturnValue) == 0x0000C0, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_Map_Find_Value_1) == 0x0000C8, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_Map_Find_Value_1' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_Map_Find_ReturnValue_1) == 0x0000D0, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_Map_Find_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_Map_Find_Value_2) == 0x0000D8, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_Map_Find_Value_2' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_Map_Find_ReturnValue_2) == 0x0000E0, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_Map_Find_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_SetVisibilityFromBool_SameBool) == 0x0000E1, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_SetVisibilityFromBool_SameBool' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_SetVisibilityFromBool_SameBool_1) == 0x0000E2, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_SetVisibilityFromBool_SameBool_1' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_Map_Find_Value_3) == 0x0000E8, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_Map_Find_Value_3' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_Map_Find_ReturnValue_3) == 0x0000F0, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_Map_Find_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_Map_Find_Value_4) == 0x0000F8, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_Map_Find_Value_4' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_Map_Find_ReturnValue_4) == 0x000100, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_Map_Find_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_Map_Find_Value_5) == 0x000108, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_Map_Find_Value_5' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_Map_Find_ReturnValue_5) == 0x000110, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_Map_Find_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_SetVisibilityFromBool_SameBool_2) == 0x000111, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_SetVisibilityFromBool_SameBool_2' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_SetVisibilityFromBool_SameBool_3) == 0x000112, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_SetVisibilityFromBool_SameBool_3' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_SetVisibilityFromBool_SameBool_4) == 0x000113, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_SetVisibilityFromBool_SameBool_4' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_Map_Find_Value_6) == 0x000118, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_Map_Find_Value_6' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_Map_Find_ReturnValue_6) == 0x000120, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_Map_Find_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_Map_Find_Value_7) == 0x000128, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_Map_Find_Value_7' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_Map_Find_ReturnValue_7) == 0x000130, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_Map_Find_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_SetVisibilityFromBool_SameBool_5) == 0x000131, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_SetVisibilityFromBool_SameBool_5' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_Map_Find_Value_8) == 0x000138, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_Map_Find_Value_8' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_Map_Find_ReturnValue_8) == 0x000140, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_Map_Find_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_SetVisibilityFromBool_SameBool_6) == 0x000141, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_SetVisibilityFromBool_SameBool_6' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_SetVisibilityFromBool_SameBool_7) == 0x000142, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_SetVisibilityFromBool_SameBool_7' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_SetVisibilityFromBool_SameBool_8) == 0x000143, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_SetVisibilityFromBool_SameBool_8' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_IsValid_ReturnValue) == 0x000144, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_Map_Find_Value_9) == 0x000148, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_Map_Find_Value_9' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_Map_Find_ReturnValue_9) == 0x000150, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_Map_Find_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_SetVisibilityFromBool_SameBool_9) == 0x000151, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_SetVisibilityFromBool_SameBool_9' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_IsValid_ReturnValue_1) == 0x000152, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Map_Buttons, CallFunc_IsGamepadCrosshairHovering_Hovering) == 0x000153, "Member 'W_Premission_Tablet_Overlay_C_Update_Map_Buttons::CallFunc_IsGamepadCrosshairHovering_Hovering' has a wrong offset!");

// Function W_Premission_Tablet_Overlay.W_Premission_Tablet_Overlay_C.Update Roster Buttons
// 0x0060 (0x0060 - 0x0000)
struct W_Premission_Tablet_Overlay_C_Update_Roster_Buttons final
{
public:
	class FString                                 Temp_string_Variable;                              // 0x0000(0x0010)(ConstParm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Temp_string_Variable_1;                            // 0x0010(0x0010)(ConstParm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Temp_string_Variable_2;                            // 0x0020(0x0010)(ConstParm, ZeroConstructor, HasGetValueTypeHash)
	class UW_ScreenFooterEntry_C*                 CallFunc_Map_Find_Value;                           // 0x0030(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_ScreenFooterEntry_C*                 CallFunc_Map_Find_Value_1;                         // 0x0040(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_1;                   // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_ScreenFooterEntry_C*                 CallFunc_Map_Find_Value_2;                         // 0x0050(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_2;                   // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetVisibilityFromBool_SameBool;           // 0x0059(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetVisibilityFromBool_SameBool_1;         // 0x005A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetVisibilityFromBool_SameBool_2;         // 0x005B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_Premission_Tablet_Overlay_C_Update_Roster_Buttons) == 0x000008, "Wrong alignment on W_Premission_Tablet_Overlay_C_Update_Roster_Buttons");
static_assert(sizeof(W_Premission_Tablet_Overlay_C_Update_Roster_Buttons) == 0x000060, "Wrong size on W_Premission_Tablet_Overlay_C_Update_Roster_Buttons");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Roster_Buttons, Temp_string_Variable) == 0x000000, "Member 'W_Premission_Tablet_Overlay_C_Update_Roster_Buttons::Temp_string_Variable' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Roster_Buttons, Temp_string_Variable_1) == 0x000010, "Member 'W_Premission_Tablet_Overlay_C_Update_Roster_Buttons::Temp_string_Variable_1' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Roster_Buttons, Temp_string_Variable_2) == 0x000020, "Member 'W_Premission_Tablet_Overlay_C_Update_Roster_Buttons::Temp_string_Variable_2' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Roster_Buttons, CallFunc_Map_Find_Value) == 0x000030, "Member 'W_Premission_Tablet_Overlay_C_Update_Roster_Buttons::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Roster_Buttons, CallFunc_Map_Find_ReturnValue) == 0x000038, "Member 'W_Premission_Tablet_Overlay_C_Update_Roster_Buttons::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Roster_Buttons, CallFunc_Map_Find_Value_1) == 0x000040, "Member 'W_Premission_Tablet_Overlay_C_Update_Roster_Buttons::CallFunc_Map_Find_Value_1' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Roster_Buttons, CallFunc_Map_Find_ReturnValue_1) == 0x000048, "Member 'W_Premission_Tablet_Overlay_C_Update_Roster_Buttons::CallFunc_Map_Find_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Roster_Buttons, CallFunc_Map_Find_Value_2) == 0x000050, "Member 'W_Premission_Tablet_Overlay_C_Update_Roster_Buttons::CallFunc_Map_Find_Value_2' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Roster_Buttons, CallFunc_Map_Find_ReturnValue_2) == 0x000058, "Member 'W_Premission_Tablet_Overlay_C_Update_Roster_Buttons::CallFunc_Map_Find_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Roster_Buttons, CallFunc_SetVisibilityFromBool_SameBool) == 0x000059, "Member 'W_Premission_Tablet_Overlay_C_Update_Roster_Buttons::CallFunc_SetVisibilityFromBool_SameBool' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Roster_Buttons, CallFunc_SetVisibilityFromBool_SameBool_1) == 0x00005A, "Member 'W_Premission_Tablet_Overlay_C_Update_Roster_Buttons::CallFunc_SetVisibilityFromBool_SameBool_1' has a wrong offset!");
static_assert(offsetof(W_Premission_Tablet_Overlay_C_Update_Roster_Buttons, CallFunc_SetVisibilityFromBool_SameBool_2) == 0x00005B, "Member 'W_Premission_Tablet_Overlay_C_Update_Roster_Buttons::CallFunc_SetVisibilityFromBool_SameBool_2' has a wrong offset!");

}

