#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_PreMission_Tablet_Brief_Overview

#include "Basic.hpp"

#include "CommonUI_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_PreMission_Tablet_Brief_Overview.W_PreMission_Tablet_Brief_Overview_C
// 0x0088 (0x0498 - 0x0410)
class UW_PreMission_Tablet_Brief_Overview_C final : public UCommonActivatableWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0410(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UScrollBox*                             ContentScrollBox;                                  // 0x0418(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_PreMission_Tablet_Brief_Audio_C*     DispatchAudioPlayer;                               // 0x0420(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 img_MissionImage;                                  // 0x0428(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_Text_C*                              lbl_Mission;                                       // 0x0430(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_Text_C*                              lbl_Situation;                                     // 0x0438(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       txt_MissionBriefTranscript;                        // 0x0440(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_Text_C*                              txt_MissionDescription;                            // 0x0448(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_Text_C*                              txt_SituationDescription;                          // 0x0450(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_Text_C*                              txt_SituationType;                                 // 0x0458(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VB_Overview;                                       // 0x0460(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_TabletText_C*                        W_TabletText_BriefTranscript;                      // 0x0468(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_TabletText_C*                        W_TabletText_Mission;                              // 0x0470(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              OnPlayDispatchAudio;                               // 0x0478(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void()>              OnStopDispatchAudio;                               // 0x0488(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void BndEvt__W_PreMission_Tablet_Brief_Overview_DispatchAudioPlayer_K2Node_ComponentBoundEvent_0_OnPlay__DelegateSignature();
	void BndEvt__W_PreMission_Tablet_Brief_Overview_DispatchAudioPlayer_K2Node_ComponentBoundEvent_1_OnStop__DelegateSignature();
	void BndEvt__W_PreMission_Tablet_Brief_Overview_DispatchAudioPlayer_K2Node_ComponentBoundEvent_2_OnPause__DelegateSignature();
	void ExecuteUbergraph_W_PreMission_Tablet_Brief_Overview(int32 EntryPoint);
	void IsAudioPlaying(bool* IsPlaying);
	struct FEventReply OnAnalogValueChanged(const struct FGeometry& MyGeometry, const struct FAnalogInputEvent& InAnalogInputEvent);
	struct FEventReply OnKeyUp(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent);
	struct FEventReply OnPreviewKeyDown(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent);

	class UWidget* BP_GetDesiredFocusTarget() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_PreMission_Tablet_Brief_Overview_C">();
	}
	static class UW_PreMission_Tablet_Brief_Overview_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_PreMission_Tablet_Brief_Overview_C>();
	}
};
static_assert(alignof(UW_PreMission_Tablet_Brief_Overview_C) == 0x000008, "Wrong alignment on UW_PreMission_Tablet_Brief_Overview_C");
static_assert(sizeof(UW_PreMission_Tablet_Brief_Overview_C) == 0x000498, "Wrong size on UW_PreMission_Tablet_Brief_Overview_C");
static_assert(offsetof(UW_PreMission_Tablet_Brief_Overview_C, UberGraphFrame) == 0x000410, "Member 'UW_PreMission_Tablet_Brief_Overview_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UW_PreMission_Tablet_Brief_Overview_C, ContentScrollBox) == 0x000418, "Member 'UW_PreMission_Tablet_Brief_Overview_C::ContentScrollBox' has a wrong offset!");
static_assert(offsetof(UW_PreMission_Tablet_Brief_Overview_C, DispatchAudioPlayer) == 0x000420, "Member 'UW_PreMission_Tablet_Brief_Overview_C::DispatchAudioPlayer' has a wrong offset!");
static_assert(offsetof(UW_PreMission_Tablet_Brief_Overview_C, img_MissionImage) == 0x000428, "Member 'UW_PreMission_Tablet_Brief_Overview_C::img_MissionImage' has a wrong offset!");
static_assert(offsetof(UW_PreMission_Tablet_Brief_Overview_C, lbl_Mission) == 0x000430, "Member 'UW_PreMission_Tablet_Brief_Overview_C::lbl_Mission' has a wrong offset!");
static_assert(offsetof(UW_PreMission_Tablet_Brief_Overview_C, lbl_Situation) == 0x000438, "Member 'UW_PreMission_Tablet_Brief_Overview_C::lbl_Situation' has a wrong offset!");
static_assert(offsetof(UW_PreMission_Tablet_Brief_Overview_C, txt_MissionBriefTranscript) == 0x000440, "Member 'UW_PreMission_Tablet_Brief_Overview_C::txt_MissionBriefTranscript' has a wrong offset!");
static_assert(offsetof(UW_PreMission_Tablet_Brief_Overview_C, txt_MissionDescription) == 0x000448, "Member 'UW_PreMission_Tablet_Brief_Overview_C::txt_MissionDescription' has a wrong offset!");
static_assert(offsetof(UW_PreMission_Tablet_Brief_Overview_C, txt_SituationDescription) == 0x000450, "Member 'UW_PreMission_Tablet_Brief_Overview_C::txt_SituationDescription' has a wrong offset!");
static_assert(offsetof(UW_PreMission_Tablet_Brief_Overview_C, txt_SituationType) == 0x000458, "Member 'UW_PreMission_Tablet_Brief_Overview_C::txt_SituationType' has a wrong offset!");
static_assert(offsetof(UW_PreMission_Tablet_Brief_Overview_C, VB_Overview) == 0x000460, "Member 'UW_PreMission_Tablet_Brief_Overview_C::VB_Overview' has a wrong offset!");
static_assert(offsetof(UW_PreMission_Tablet_Brief_Overview_C, W_TabletText_BriefTranscript) == 0x000468, "Member 'UW_PreMission_Tablet_Brief_Overview_C::W_TabletText_BriefTranscript' has a wrong offset!");
static_assert(offsetof(UW_PreMission_Tablet_Brief_Overview_C, W_TabletText_Mission) == 0x000470, "Member 'UW_PreMission_Tablet_Brief_Overview_C::W_TabletText_Mission' has a wrong offset!");
static_assert(offsetof(UW_PreMission_Tablet_Brief_Overview_C, OnPlayDispatchAudio) == 0x000478, "Member 'UW_PreMission_Tablet_Brief_Overview_C::OnPlayDispatchAudio' has a wrong offset!");
static_assert(offsetof(UW_PreMission_Tablet_Brief_Overview_C, OnStopDispatchAudio) == 0x000488, "Member 'UW_PreMission_Tablet_Brief_Overview_C::OnStopDispatchAudio' has a wrong offset!");

}

