#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_RadialIcon_MapMarking

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "ST_Commands_structs.hpp"
#include "ReadyOrNot_structs.hpp"
#include "FBasicIconSettings_structs.hpp"
#include "UMG_classes.hpp"
#include "EIconAnimationStyles_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_RadialIcon_MapMarking.W_RadialIcon_MapMarking_C
// 0x01B0 (0x0470 - 0x02C0)
class UW_RadialIcon_MapMarking_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Select;                                            // 0x02C8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Shake;                                             // 0x02D0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Grow;                                              // 0x02D8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Icon;                                              // 0x02E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               Sizer;                                             // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FString                                 ID;                                                // 0x02F0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)
	class FText                                   DisplayName;                                       // 0x0300(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)
	class UTexture2D*                             IconImage;                                         // 0x0318(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          HasSubCommands;                                    // 0x0320(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_321[0x7];                                      // 0x0321(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FST_Commands                           CommandStructure;                                  // 0x0328(0x0070)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	struct FSwatCommand                           SwatCommand;                                       // 0x0398(0x0060)(Edit, BlueprintVisible)
	double                                        IconSize;                                          // 0x03F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	struct FFBasicIconSettings                    Settings;                                          // 0x0400(0x0028)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	struct FLinearColor                           CurrentColor;                                      // 0x0428(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Highlighted;                                       // 0x0438(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_439[0x7];                                      // 0x0439(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Alpha;                                             // 0x0440(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   IconText;                                          // 0x0448(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	EPreMissionSubCategory                        SubCategory;                                       // 0x0460(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_461[0x7];                                      // 0x0461(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                PreMissionPlanning;                                // 0x0468(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void Construct();
	void ExecuteUbergraph_W_RadialIcon_MapMarking(int32 EntryPoint);
	struct FLinearColor Get_Icon_ColorAndOpacity_0();
	void OnHighlight(bool Selected_0);
	void OnUnhighlight(bool Unselected);
	void PreConstruct(bool IsDesignTime);
	void Selected();
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_RadialIcon_MapMarking_C">();
	}
	static class UW_RadialIcon_MapMarking_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_RadialIcon_MapMarking_C>();
	}
};
static_assert(alignof(UW_RadialIcon_MapMarking_C) == 0x000008, "Wrong alignment on UW_RadialIcon_MapMarking_C");
static_assert(sizeof(UW_RadialIcon_MapMarking_C) == 0x000470, "Wrong size on UW_RadialIcon_MapMarking_C");
static_assert(offsetof(UW_RadialIcon_MapMarking_C, UberGraphFrame) == 0x0002C0, "Member 'UW_RadialIcon_MapMarking_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UW_RadialIcon_MapMarking_C, Select) == 0x0002C8, "Member 'UW_RadialIcon_MapMarking_C::Select' has a wrong offset!");
static_assert(offsetof(UW_RadialIcon_MapMarking_C, Shake) == 0x0002D0, "Member 'UW_RadialIcon_MapMarking_C::Shake' has a wrong offset!");
static_assert(offsetof(UW_RadialIcon_MapMarking_C, Grow) == 0x0002D8, "Member 'UW_RadialIcon_MapMarking_C::Grow' has a wrong offset!");
static_assert(offsetof(UW_RadialIcon_MapMarking_C, Icon) == 0x0002E0, "Member 'UW_RadialIcon_MapMarking_C::Icon' has a wrong offset!");
static_assert(offsetof(UW_RadialIcon_MapMarking_C, Sizer) == 0x0002E8, "Member 'UW_RadialIcon_MapMarking_C::Sizer' has a wrong offset!");
static_assert(offsetof(UW_RadialIcon_MapMarking_C, ID) == 0x0002F0, "Member 'UW_RadialIcon_MapMarking_C::ID' has a wrong offset!");
static_assert(offsetof(UW_RadialIcon_MapMarking_C, DisplayName) == 0x000300, "Member 'UW_RadialIcon_MapMarking_C::DisplayName' has a wrong offset!");
static_assert(offsetof(UW_RadialIcon_MapMarking_C, IconImage) == 0x000318, "Member 'UW_RadialIcon_MapMarking_C::IconImage' has a wrong offset!");
static_assert(offsetof(UW_RadialIcon_MapMarking_C, HasSubCommands) == 0x000320, "Member 'UW_RadialIcon_MapMarking_C::HasSubCommands' has a wrong offset!");
static_assert(offsetof(UW_RadialIcon_MapMarking_C, CommandStructure) == 0x000328, "Member 'UW_RadialIcon_MapMarking_C::CommandStructure' has a wrong offset!");
static_assert(offsetof(UW_RadialIcon_MapMarking_C, SwatCommand) == 0x000398, "Member 'UW_RadialIcon_MapMarking_C::SwatCommand' has a wrong offset!");
static_assert(offsetof(UW_RadialIcon_MapMarking_C, IconSize) == 0x0003F8, "Member 'UW_RadialIcon_MapMarking_C::IconSize' has a wrong offset!");
static_assert(offsetof(UW_RadialIcon_MapMarking_C, Settings) == 0x000400, "Member 'UW_RadialIcon_MapMarking_C::Settings' has a wrong offset!");
static_assert(offsetof(UW_RadialIcon_MapMarking_C, CurrentColor) == 0x000428, "Member 'UW_RadialIcon_MapMarking_C::CurrentColor' has a wrong offset!");
static_assert(offsetof(UW_RadialIcon_MapMarking_C, Highlighted) == 0x000438, "Member 'UW_RadialIcon_MapMarking_C::Highlighted' has a wrong offset!");
static_assert(offsetof(UW_RadialIcon_MapMarking_C, Alpha) == 0x000440, "Member 'UW_RadialIcon_MapMarking_C::Alpha' has a wrong offset!");
static_assert(offsetof(UW_RadialIcon_MapMarking_C, IconText) == 0x000448, "Member 'UW_RadialIcon_MapMarking_C::IconText' has a wrong offset!");
static_assert(offsetof(UW_RadialIcon_MapMarking_C, SubCategory) == 0x000460, "Member 'UW_RadialIcon_MapMarking_C::SubCategory' has a wrong offset!");
static_assert(offsetof(UW_RadialIcon_MapMarking_C, PreMissionPlanning) == 0x000468, "Member 'UW_RadialIcon_MapMarking_C::PreMissionPlanning' has a wrong offset!");

}

