#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_RosterReview_EventCard

#include "Basic.hpp"

#include "CommonUI_classes.hpp"
#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "ReadyOrNot_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_RosterReview_EventCard.W_RosterReview_EventCard_C
// 0x01F0 (0x0600 - 0x0410)
class UW_RosterReview_EventCard_C final : public UCommonActivatableWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0410(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       animRevealEventDetails;                            // 0x0418(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       animReveal;                                        // 0x0420(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UCommonButton_C*                        btn_Card;                                          // 0x0428(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                EventOverlay;                                      // 0x0430(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 HoverBorder;                                       // 0x0438(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 icn_Event;                                         // 0x0440(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 icn_StatusChange;                                  // 0x0448(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_53;                                          // 0x0450(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 img_PositionCorner;                                // 0x0458(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       lbl_Unknown;                                       // 0x0460(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         OverviewDetailsBox_1;                              // 0x0468(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             OverviewPosition;                                  // 0x0470(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           OverviewStatusBox;                                 // 0x0478(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Portrait_Full;                                     // 0x0480(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Position;                                          // 0x0488(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 PositionColorBorder;                               // 0x0490(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       PositionNumber;                                    // 0x0498(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ProfileImage;                                      // 0x04A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonRichTextBlock*                   rtxt_EventDescription;                             // 0x04A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               Size_EventDetails;                                 // 0x04B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                Status;                                            // 0x04B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                StatusBorder;                                      // 0x04C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               TraitOverlay;                                      // 0x04C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       txt_EventDetailTitle;                              // 0x04D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       txt_EventTitle;                                    // 0x04D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             txt_FirstName;                                     // 0x04E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             txt_LastName;                                      // 0x04E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       txt_Status;                                        // 0x04F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       txt_TraitUnlocked;                                 // 0x04F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VB_Card;                                           // 0x0500(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class URosterCharacter*                       RosterCharacter;                                   // 0x0508(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FSlateBrush                            BlankPortrait;                                     // 0x0510(0x00D0)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          ShowEventDetails;                                  // 0x05E0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_5E1[0x7];                                      // 0x05E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              OnDetailsRevealed;                                 // 0x05E8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void BackPage(bool* Handled);
	void BlankDetails();
	void ChangePage(class FName PageName);
	void Construct();
	void ExecuteUbergraph_W_RosterReview_EventCard(int32 EntryPoint);
	void Finished_AF9B49AA4F6E19FB623872BB985C4A7D();
	void Finished_BA9218A1476038BD6635859D68F86118();
	void GetInvisibleDuringShowDetails(ESlateVisibility* Visibility_0);
	void Hide(double Delay, bool Collapse);
	void PreConstruct(bool IsDesignTime);
	void Reveal(double Delay);
	void SetCharacter(class URosterCharacter* Character);
	void SetInputMode(bool IsGamepad);
	void SetPosition(ERosterSquadPosition Position_0);
	void UpdateStyleByState(ERosterCharacterState State);

	void GetFocusTarget(class UWidget** Focus) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_RosterReview_EventCard_C">();
	}
	static class UW_RosterReview_EventCard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_RosterReview_EventCard_C>();
	}
};
static_assert(alignof(UW_RosterReview_EventCard_C) == 0x000010, "Wrong alignment on UW_RosterReview_EventCard_C");
static_assert(sizeof(UW_RosterReview_EventCard_C) == 0x000600, "Wrong size on UW_RosterReview_EventCard_C");
static_assert(offsetof(UW_RosterReview_EventCard_C, UberGraphFrame) == 0x000410, "Member 'UW_RosterReview_EventCard_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, animRevealEventDetails) == 0x000418, "Member 'UW_RosterReview_EventCard_C::animRevealEventDetails' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, animReveal) == 0x000420, "Member 'UW_RosterReview_EventCard_C::animReveal' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, btn_Card) == 0x000428, "Member 'UW_RosterReview_EventCard_C::btn_Card' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, EventOverlay) == 0x000430, "Member 'UW_RosterReview_EventCard_C::EventOverlay' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, HoverBorder) == 0x000438, "Member 'UW_RosterReview_EventCard_C::HoverBorder' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, icn_Event) == 0x000440, "Member 'UW_RosterReview_EventCard_C::icn_Event' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, icn_StatusChange) == 0x000448, "Member 'UW_RosterReview_EventCard_C::icn_StatusChange' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, Image_53) == 0x000450, "Member 'UW_RosterReview_EventCard_C::Image_53' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, img_PositionCorner) == 0x000458, "Member 'UW_RosterReview_EventCard_C::img_PositionCorner' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, lbl_Unknown) == 0x000460, "Member 'UW_RosterReview_EventCard_C::lbl_Unknown' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, OverviewDetailsBox_1) == 0x000468, "Member 'UW_RosterReview_EventCard_C::OverviewDetailsBox_1' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, OverviewPosition) == 0x000470, "Member 'UW_RosterReview_EventCard_C::OverviewPosition' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, OverviewStatusBox) == 0x000478, "Member 'UW_RosterReview_EventCard_C::OverviewStatusBox' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, Portrait_Full) == 0x000480, "Member 'UW_RosterReview_EventCard_C::Portrait_Full' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, Position) == 0x000488, "Member 'UW_RosterReview_EventCard_C::Position' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, PositionColorBorder) == 0x000490, "Member 'UW_RosterReview_EventCard_C::PositionColorBorder' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, PositionNumber) == 0x000498, "Member 'UW_RosterReview_EventCard_C::PositionNumber' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, ProfileImage) == 0x0004A0, "Member 'UW_RosterReview_EventCard_C::ProfileImage' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, rtxt_EventDescription) == 0x0004A8, "Member 'UW_RosterReview_EventCard_C::rtxt_EventDescription' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, Size_EventDetails) == 0x0004B0, "Member 'UW_RosterReview_EventCard_C::Size_EventDetails' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, Status) == 0x0004B8, "Member 'UW_RosterReview_EventCard_C::Status' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, StatusBorder) == 0x0004C0, "Member 'UW_RosterReview_EventCard_C::StatusBorder' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, TraitOverlay) == 0x0004C8, "Member 'UW_RosterReview_EventCard_C::TraitOverlay' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, txt_EventDetailTitle) == 0x0004D0, "Member 'UW_RosterReview_EventCard_C::txt_EventDetailTitle' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, txt_EventTitle) == 0x0004D8, "Member 'UW_RosterReview_EventCard_C::txt_EventTitle' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, txt_FirstName) == 0x0004E0, "Member 'UW_RosterReview_EventCard_C::txt_FirstName' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, txt_LastName) == 0x0004E8, "Member 'UW_RosterReview_EventCard_C::txt_LastName' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, txt_Status) == 0x0004F0, "Member 'UW_RosterReview_EventCard_C::txt_Status' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, txt_TraitUnlocked) == 0x0004F8, "Member 'UW_RosterReview_EventCard_C::txt_TraitUnlocked' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, VB_Card) == 0x000500, "Member 'UW_RosterReview_EventCard_C::VB_Card' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, RosterCharacter) == 0x000508, "Member 'UW_RosterReview_EventCard_C::RosterCharacter' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, BlankPortrait) == 0x000510, "Member 'UW_RosterReview_EventCard_C::BlankPortrait' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, ShowEventDetails) == 0x0005E0, "Member 'UW_RosterReview_EventCard_C::ShowEventDetails' has a wrong offset!");
static_assert(offsetof(UW_RosterReview_EventCard_C, OnDetailsRevealed) == 0x0005E8, "Member 'UW_RosterReview_EventCard_C::OnDetailsRevealed' has a wrong offset!");

}

