#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_StreamingInstallProgress

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_StreamingInstallProgress.W_StreamingInstallProgress_C
// 0x0000 (0x0348 - 0x0348)
class UW_StreamingInstallProgress_C final : public UStreamingInstallProgress
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_StreamingInstallProgress_C">();
	}
	static class UW_StreamingInstallProgress_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_StreamingInstallProgress_C>();
	}
};
static_assert(alignof(UW_StreamingInstallProgress_C) == 0x000008, "Wrong alignment on UW_StreamingInstallProgress_C");
static_assert(sizeof(UW_StreamingInstallProgress_C) == 0x000348, "Wrong size on UW_StreamingInstallProgress_C");

}

