#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Tutorial

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "CommonInput_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function W_Tutorial.W_Tutorial_C.ExecuteUbergraph_W_Tutorial
// 0x00C0 (0x00C0 - 0x0000)
struct W_Tutorial_C_ExecuteUbergraph_W_Tutorial final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonInputSubsystem*                  CallFunc_GetLocalPlayerSubsystem_ReturnValue;      // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(ECommonInputType bNewInputType)> K2Node_CreateDelegate_OutputDelegate;            // 0x0010(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0020(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationForward_ReturnValue;         // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	ECommonInputType                              K2Node_Event_InputType;                            // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetDescription_ReturnValue;               // 0x0040(0x0018)()
	class FText                                   CallFunc_GetTitle_ReturnValue;                     // 0x0058(0x0018)()
	float                                         CallFunc_GetAnimationCurrentTime_ReturnValue;      // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_74[0x4];                                       // 0x0074(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationReverse_ReturnValue;         // 0x0078(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_DoubleDouble_ReturnValue;            // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsAnimationPlaying_ReturnValue;           // 0x0081(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0082(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsAnimationPlayingForward_ReturnValue;    // 0x0083(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0084(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_85[0x3];                                       // 0x0085(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_PauseAnimation_ReturnValue;               // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue;                    // 0x008C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8D[0x3];                                       // 0x008D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0090(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x0098(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AReadyOrNotPlayerController*            CallFunc_GetReadyOrNotPlayerController_ReturnValue; // 0x00A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetShowFooter_ReturnValue;                // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetShowFooter_ReturnValue_1;              // 0x00B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B2[0x6];                                       // 0x00B2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Less_DoubleDouble_A_ImplicitCast;         // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_Tutorial_C_ExecuteUbergraph_W_Tutorial) == 0x000008, "Wrong alignment on W_Tutorial_C_ExecuteUbergraph_W_Tutorial");
static_assert(sizeof(W_Tutorial_C_ExecuteUbergraph_W_Tutorial) == 0x0000C0, "Wrong size on W_Tutorial_C_ExecuteUbergraph_W_Tutorial");
static_assert(offsetof(W_Tutorial_C_ExecuteUbergraph_W_Tutorial, EntryPoint) == 0x000000, "Member 'W_Tutorial_C_ExecuteUbergraph_W_Tutorial::EntryPoint' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_ExecuteUbergraph_W_Tutorial, CallFunc_GetLocalPlayerSubsystem_ReturnValue) == 0x000008, "Member 'W_Tutorial_C_ExecuteUbergraph_W_Tutorial::CallFunc_GetLocalPlayerSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_ExecuteUbergraph_W_Tutorial, K2Node_CreateDelegate_OutputDelegate) == 0x000010, "Member 'W_Tutorial_C_ExecuteUbergraph_W_Tutorial::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_ExecuteUbergraph_W_Tutorial, K2Node_CreateDelegate_OutputDelegate_1) == 0x000020, "Member 'W_Tutorial_C_ExecuteUbergraph_W_Tutorial::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_ExecuteUbergraph_W_Tutorial, CallFunc_PlayAnimationForward_ReturnValue) == 0x000030, "Member 'W_Tutorial_C_ExecuteUbergraph_W_Tutorial::CallFunc_PlayAnimationForward_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_ExecuteUbergraph_W_Tutorial, K2Node_Event_InputType) == 0x000038, "Member 'W_Tutorial_C_ExecuteUbergraph_W_Tutorial::K2Node_Event_InputType' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_ExecuteUbergraph_W_Tutorial, CallFunc_GetDescription_ReturnValue) == 0x000040, "Member 'W_Tutorial_C_ExecuteUbergraph_W_Tutorial::CallFunc_GetDescription_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_ExecuteUbergraph_W_Tutorial, CallFunc_GetTitle_ReturnValue) == 0x000058, "Member 'W_Tutorial_C_ExecuteUbergraph_W_Tutorial::CallFunc_GetTitle_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_ExecuteUbergraph_W_Tutorial, CallFunc_GetAnimationCurrentTime_ReturnValue) == 0x000070, "Member 'W_Tutorial_C_ExecuteUbergraph_W_Tutorial::CallFunc_GetAnimationCurrentTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_ExecuteUbergraph_W_Tutorial, CallFunc_PlayAnimationReverse_ReturnValue) == 0x000078, "Member 'W_Tutorial_C_ExecuteUbergraph_W_Tutorial::CallFunc_PlayAnimationReverse_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_ExecuteUbergraph_W_Tutorial, CallFunc_Less_DoubleDouble_ReturnValue) == 0x000080, "Member 'W_Tutorial_C_ExecuteUbergraph_W_Tutorial::CallFunc_Less_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_ExecuteUbergraph_W_Tutorial, CallFunc_IsAnimationPlaying_ReturnValue) == 0x000081, "Member 'W_Tutorial_C_ExecuteUbergraph_W_Tutorial::CallFunc_IsAnimationPlaying_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_ExecuteUbergraph_W_Tutorial, CallFunc_BooleanAND_ReturnValue) == 0x000082, "Member 'W_Tutorial_C_ExecuteUbergraph_W_Tutorial::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_ExecuteUbergraph_W_Tutorial, CallFunc_IsAnimationPlayingForward_ReturnValue) == 0x000083, "Member 'W_Tutorial_C_ExecuteUbergraph_W_Tutorial::CallFunc_IsAnimationPlayingForward_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_ExecuteUbergraph_W_Tutorial, CallFunc_Not_PreBool_ReturnValue) == 0x000084, "Member 'W_Tutorial_C_ExecuteUbergraph_W_Tutorial::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_ExecuteUbergraph_W_Tutorial, CallFunc_PauseAnimation_ReturnValue) == 0x000088, "Member 'W_Tutorial_C_ExecuteUbergraph_W_Tutorial::CallFunc_PauseAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_ExecuteUbergraph_W_Tutorial, CallFunc_IsVisible_ReturnValue) == 0x00008C, "Member 'W_Tutorial_C_ExecuteUbergraph_W_Tutorial::CallFunc_IsVisible_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_ExecuteUbergraph_W_Tutorial, CallFunc_PlayAnimation_ReturnValue) == 0x000090, "Member 'W_Tutorial_C_ExecuteUbergraph_W_Tutorial::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_ExecuteUbergraph_W_Tutorial, K2Node_CreateDelegate_OutputDelegate_2) == 0x000098, "Member 'W_Tutorial_C_ExecuteUbergraph_W_Tutorial::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_ExecuteUbergraph_W_Tutorial, CallFunc_GetReadyOrNotPlayerController_ReturnValue) == 0x0000A8, "Member 'W_Tutorial_C_ExecuteUbergraph_W_Tutorial::CallFunc_GetReadyOrNotPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_ExecuteUbergraph_W_Tutorial, CallFunc_GetShowFooter_ReturnValue) == 0x0000B0, "Member 'W_Tutorial_C_ExecuteUbergraph_W_Tutorial::CallFunc_GetShowFooter_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_ExecuteUbergraph_W_Tutorial, CallFunc_GetShowFooter_ReturnValue_1) == 0x0000B1, "Member 'W_Tutorial_C_ExecuteUbergraph_W_Tutorial::CallFunc_GetShowFooter_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_ExecuteUbergraph_W_Tutorial, CallFunc_Less_DoubleDouble_A_ImplicitCast) == 0x0000B8, "Member 'W_Tutorial_C_ExecuteUbergraph_W_Tutorial::CallFunc_Less_DoubleDouble_A_ImplicitCast' has a wrong offset!");

// Function W_Tutorial.W_Tutorial_C.GetDefaultTextStyleOverride
// 0x00C8 (0x00C8 - 0x0000)
struct W_Tutorial_C_GetDefaultTextStyleOverride final
{
public:
	struct FSlateFontInfo                         TextBlockStyle;                                    // 0x0000(0x0058)(Parm, OutParm, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPcPlatform_ReturnValue;                 // 0x0059(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5A[0x6];                                       // 0x005A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 K2Node_Select_Default;                             // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UCommonTextStyle*                       CallFunc_GetClassDefaultObject_ReturnValue;        // 0x0068(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FSlateFontInfo                         CallFunc_GetFont_OutFont;                          // 0x0070(0x0058)(HasGetValueTypeHash)
};
static_assert(alignof(W_Tutorial_C_GetDefaultTextStyleOverride) == 0x000008, "Wrong alignment on W_Tutorial_C_GetDefaultTextStyleOverride");
static_assert(sizeof(W_Tutorial_C_GetDefaultTextStyleOverride) == 0x0000C8, "Wrong size on W_Tutorial_C_GetDefaultTextStyleOverride");
static_assert(offsetof(W_Tutorial_C_GetDefaultTextStyleOverride, TextBlockStyle) == 0x000000, "Member 'W_Tutorial_C_GetDefaultTextStyleOverride::TextBlockStyle' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_GetDefaultTextStyleOverride, Temp_bool_Variable) == 0x000058, "Member 'W_Tutorial_C_GetDefaultTextStyleOverride::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_GetDefaultTextStyleOverride, CallFunc_IsPcPlatform_ReturnValue) == 0x000059, "Member 'W_Tutorial_C_GetDefaultTextStyleOverride::CallFunc_IsPcPlatform_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_GetDefaultTextStyleOverride, K2Node_Select_Default) == 0x000060, "Member 'W_Tutorial_C_GetDefaultTextStyleOverride::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_GetDefaultTextStyleOverride, CallFunc_GetClassDefaultObject_ReturnValue) == 0x000068, "Member 'W_Tutorial_C_GetDefaultTextStyleOverride::CallFunc_GetClassDefaultObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_GetDefaultTextStyleOverride, CallFunc_GetFont_OutFont) == 0x000070, "Member 'W_Tutorial_C_GetDefaultTextStyleOverride::CallFunc_GetFont_OutFont' has a wrong offset!");

// Function W_Tutorial.W_Tutorial_C.RefreshWidget
// 0x0001 (0x0001 - 0x0000)
struct W_Tutorial_C_RefreshWidget final
{
public:
	ECommonInputType                              InputType;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_Tutorial_C_RefreshWidget) == 0x000001, "Wrong alignment on W_Tutorial_C_RefreshWidget");
static_assert(sizeof(W_Tutorial_C_RefreshWidget) == 0x000001, "Wrong size on W_Tutorial_C_RefreshWidget");
static_assert(offsetof(W_Tutorial_C_RefreshWidget, InputType) == 0x000000, "Member 'W_Tutorial_C_RefreshWidget::InputType' has a wrong offset!");

// Function W_Tutorial.W_Tutorial_C.UpdateFooterVisibility
// 0x0005 (0x0005 - 0x0000)
struct W_Tutorial_C_UpdateFooterVisibility final
{
public:
	bool                                          Temp_bool_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetShowFooter_ReturnValue;                // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_Tutorial_C_UpdateFooterVisibility) == 0x000001, "Wrong alignment on W_Tutorial_C_UpdateFooterVisibility");
static_assert(sizeof(W_Tutorial_C_UpdateFooterVisibility) == 0x000005, "Wrong size on W_Tutorial_C_UpdateFooterVisibility");
static_assert(offsetof(W_Tutorial_C_UpdateFooterVisibility, Temp_bool_Variable) == 0x000000, "Member 'W_Tutorial_C_UpdateFooterVisibility::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_UpdateFooterVisibility, Temp_byte_Variable) == 0x000001, "Member 'W_Tutorial_C_UpdateFooterVisibility::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_UpdateFooterVisibility, Temp_byte_Variable_1) == 0x000002, "Member 'W_Tutorial_C_UpdateFooterVisibility::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_UpdateFooterVisibility, CallFunc_GetShowFooter_ReturnValue) == 0x000003, "Member 'W_Tutorial_C_UpdateFooterVisibility::CallFunc_GetShowFooter_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_UpdateFooterVisibility, K2Node_Select_Default) == 0x000004, "Member 'W_Tutorial_C_UpdateFooterVisibility::K2Node_Select_Default' has a wrong offset!");

// Function W_Tutorial.W_Tutorial_C.UpdatePlatformFonts
// 0x0070 (0x0070 - 0x0000)
struct W_Tutorial_C_UpdatePlatformFonts final
{
public:
	bool                                          Temp_bool_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateFontInfo                         CallFunc_GetDefaultTextStyleOverride_TextBlockStyle; // 0x0008(0x0058)(HasGetValueTypeHash)
	bool                                          CallFunc_IsPcPlatform_ReturnValue;                 // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UDataTable*                             K2Node_Select_Default;                             // 0x0068(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_Tutorial_C_UpdatePlatformFonts) == 0x000008, "Wrong alignment on W_Tutorial_C_UpdatePlatformFonts");
static_assert(sizeof(W_Tutorial_C_UpdatePlatformFonts) == 0x000070, "Wrong size on W_Tutorial_C_UpdatePlatformFonts");
static_assert(offsetof(W_Tutorial_C_UpdatePlatformFonts, Temp_bool_Variable) == 0x000000, "Member 'W_Tutorial_C_UpdatePlatformFonts::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_UpdatePlatformFonts, CallFunc_GetDefaultTextStyleOverride_TextBlockStyle) == 0x000008, "Member 'W_Tutorial_C_UpdatePlatformFonts::CallFunc_GetDefaultTextStyleOverride_TextBlockStyle' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_UpdatePlatformFonts, CallFunc_IsPcPlatform_ReturnValue) == 0x000060, "Member 'W_Tutorial_C_UpdatePlatformFonts::CallFunc_IsPcPlatform_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Tutorial_C_UpdatePlatformFonts, K2Node_Select_Default) == 0x000068, "Member 'W_Tutorial_C_UpdatePlatformFonts::K2Node_Select_Default' has a wrong offset!");

}

